// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.31/esri/copyright.txt for details.
//>>built
define(["exports","./componentsUtils"],function(k,C){function T(d){return d.map(e=>{let c="";for(let a=0;a<e;a++)c+=(65536*(1+Math.random())|0).toString(16).substring(1);return c}).join("-")}function D(d,{selector:e,id:c}){if(!d)return null;d.assignedSlot&&(d=d.assignedSlot);d=d.getRootNode();return(c?"getElementById"in d?d.getElementById(c):null:e?d.querySelector(e):null)||D(d.host||null,{selector:e,id:c})}function t(d,e){if(d){var c;(c=d.closest(e))||(d=d.getRootNode().host||null,c=t(d,e));e=c}else e=
null;return e}function U(d,e){return E(d,e)}function E(d,e){if(d){var c=e(d);if(void 0!==c)return c;({parentNode:d}=d);return E(d instanceof ShadowRoot?d.host:d,e)}}async function F(d){if(d)return"function"===typeof d?.setFocus?d.setFocus():d.focus()}function G(d){if(d)return H(d,I)[0]??d}function J(d,e){return d?Array.from(d.children||[]).filter(c=>c?.matches(e)):[]}function V(d,e,c){e=":not([slot])"===e?J(d,":not([slot])"):Array.from(d.querySelectorAll(e));e=c&&!1===c.direct?e:e.filter(b=>b.parentElement===
d);e=c?.matches?e.filter(b=>b?.matches(c.matches)):e;const a=c?.selector;return a?e.map(b=>Array.from(b.querySelectorAll(a))).reduce((b,f)=>[...b,...f],[]).filter(b=>!!b):e}function W(d,e,c){e=":not([slot])"===e?J(d,":not([slot])")[0]||null:d.querySelector(e);e=c&&!1===c.direct?e:e?.parentElement===d?e:null;e=c?.matches?e?.matches(c.matches)?e:null:e;return(d=c?.selector)?e?.querySelector(d):e}function X(d,e){return d.filter(c=>c.matches(e))}function Y(d){return d.currentTarget.assignedNodes({flatten:!0}).filter(e=>
e.nodeType===Node.TEXT_NODE).map(e=>e.textContent).join("").trim()}function K(d){return!!L(d).length}function L(d,e){return M(d.target,e)}function M(d,e){d=d.assignedElements({flatten:!0});return e?X(d,e):d}async function Z(d,e,c,a,b){function f(){requestAnimationFrame(()=>{a?.();requestAnimationFrame(()=>b?.())})}var g=window.getComputedStyle(d);c=g.transitionProperty;g=g.transitionDuration.split(",");c=c.split(",").map(h=>h.trim()).indexOf(e);const m=g[c]??g[0];if("0s"===m)f();else return new Promise(h=>
{function l(p){p.target===d&&("propertyName"in p?p.propertyName:p.animationName)===e&&(window.clearTimeout(q),d.removeEventListener("transitionstart",l),a?.())}function n(p){p.target===d&&("propertyName"in p?p.propertyName:p.animationName)===e&&(d.removeEventListener("transitionend",n),d.removeEventListener("transitioncancel",n),b?.(),h())}const q=window.setTimeout(()=>{d.removeEventListener("transitionstart",l);d.removeEventListener("transitionend",n);d.removeEventListener("transitioncancel",n);
f();h()},1E3*parseFloat(m));d.addEventListener("transitionstart",l);d.addEventListener("transitionend",n);d.addEventListener("transitioncancel",n)})}const N=()=>T([2,1,1,1,3]);var O='input:not([inert]) select:not([inert]) textarea:not([inert]) a[href]:not([inert]) button:not([inert]) [tabindex]:not(slot):not([inert]) audio[controls]:not([inert]) video[controls]:not([inert]) [contenteditable]:not([contenteditable\x3d"false"]):not([inert]) details\x3esummary:first-of-type:not([inert]) details:not([inert])'.split(" "),
u=O.join(","),P="undefined"===typeof Element,r=P?function(){}:Element.prototype.matches||Element.prototype.msMatchesSelector||Element.prototype.webkitMatchesSelector,v=!P&&Element.prototype.getRootNode?function(d){var e;return null===d||void 0===d?void 0:null===(e=d.getRootNode)||void 0===e?void 0:e.call(d)}:function(d){return null===d||void 0===d?void 0:d.ownerDocument},w=function a(e,c){var b;void 0===c&&(c=!0);var f=null===e||void 0===e?void 0:null===(b=e.getAttribute)||void 0===b?void 0:b.call(e,
"inert");return""===f||"true"===f||c&&e&&a(e.parentNode)},Q=function(e,c,a){if(w(e))return[];var b=Array.prototype.slice.apply(e.querySelectorAll(u));c&&r.call(e,u)&&b.unshift(e);return b=b.filter(a)},R=function f(c,a,b){for(var g=[],m=Array.from(c);m.length;){var h=m.shift();if(!w(h,!1))if("SLOT"===h.tagName){var l=h.assignedElements();l=f(l.length?l:h.children,!0,b);b.flatten?g.push.apply(g,l):g.push({scopeParent:h,candidates:l})}else{r.call(h,u)&&b.filter(h)&&(a||!c.includes(h))&&g.push(h);l=h.shadowRoot||
"function"===typeof b.getShadowRoot&&b.getShadowRoot(h);var n=!w(l,!1)&&(!b.shadowRootFilter||b.shadowRootFilter(h));l&&n?(l=f(!0===l?h.children:l.children,!0,b),b.flatten?g.push.apply(g,l):g.push({scopeParent:h,candidates:l})):m.unshift.apply(m,h.children)}}return g},y=function(c){if(!c)throw Error("No node provided");if(0>c.tabIndex){var a;if(!(a=/^(AUDIO|VIDEO|DETAILS)$/.test(c.tagName))){var b;a=null===c||void 0===c?void 0:null===(b=c.getAttribute)||void 0===b?void 0:b.call(c,"contenteditable");
a=""===a||"true"===a}if(a&&isNaN(parseInt(c.getAttribute("tabindex"),10)))return 0}return c.tabIndex},aa=function(c,a){return c.tabIndex===a.tabIndex?c.documentOrder-a.documentOrder:c.tabIndex-a.tabIndex},ba=function(c){return"DETAILS"===c.tagName&&Array.prototype.slice.apply(c.children).some(function(a){return"SUMMARY"===a.tagName})},ca=function(c,a){for(var b=0;b<c.length;b++)if(c[b].checked&&c[b].form===a)return c[b]},da=function(c){if(!c.name)return!0;var a=c.form||v(c),b=function(g){return a.querySelectorAll('input[type\x3d"radio"][name\x3d"'+
g+'"]')};if("undefined"!==typeof window&&"undefined"!==typeof window.CSS&&"function"===typeof window.CSS.escape)var f=b(window.CSS.escape(c.name));else try{f=b(c.name)}catch(g){return console.error("Looks like you have a radio button with a name attribute containing invalid CSS selector characters and need the CSS.escape polyfill: %s",g.message),!1}b=ca(f,c.form);return!b||b===c},S=function(c){c=c.getBoundingClientRect();var a=c.height;return 0===c.width&&0===a},ea=function(c,a){var b=a.displayCheck;
a=a.getShadowRoot;if("hidden"===getComputedStyle(c).visibility)return!0;var f=r.call(c,"details\x3esummary:first-of-type")?c.parentElement:c;if(r.call(f,"details:not([open]) *"))return!0;if(!b||"full"===b||"legacy-full"===b){if("function"===typeof a){for(f=c;c;){var g=c.parentElement,m=v(c);if(g&&!g.shadowRoot&&!0===a(g))return S(c);c=c.assignedSlot?c.assignedSlot:g||m===c.ownerDocument?g:m.host}c=f}a=c;var h;f=a&&v(a);g=null===(h=f)||void 0===h?void 0:h.host;h=!1;if(f&&f!==a){var l,n,q;for(h=!!(null!==
(l=g)&&void 0!==l&&null!==(n=l.ownerDocument)&&void 0!==n&&n.contains(g)||null!==a&&void 0!==a&&null!==(q=a.ownerDocument)&&void 0!==q&&q.contains(a));!h&&g;){var p,z,A;f=v(g);g=null===(p=f)||void 0===p?void 0:p.host;h=!(null===(z=g)||void 0===z||null===(A=z.ownerDocument)||void 0===A||!A.contains(g))}}if(h)return!c.getClientRects().length;if("legacy-full"!==b)return!0}else if("non-zero-area"===b)return S(c);return!1},x=function(c,a){var b;(b=a.disabled||w(a))||(b="INPUT"===a.tagName&&"hidden"===
a.type);if(!(c=b||ea(a,c)||ba(a)))a:{if(/^(INPUT|BUTTON|SELECT|TEXTAREA)$/.test(a.tagName))for(c=a.parentElement;c;){if("FIELDSET"===c.tagName&&c.disabled){for(b=0;b<c.children.length;b++){var f=c.children.item(b);if("LEGEND"===f.tagName){c=r.call(c,"fieldset[disabled] *")?!0:!f.contains(a);break a}}c=!0;break a}c=c.parentElement}c=!1}return c?!1:!0},B=function(c,a){return"INPUT"===a.tagName&&"radio"===a.type&&!da(a)||0>y(a)||!x(c,a)?!1:!0},fa=function(c){c=parseInt(c.getAttribute("tabindex"),10);
return isNaN(c)||0<=c?!0:!1},ha=function b(a){var f=[],g=[];a.forEach(function(m,h){var l=!!m.scopeParent,n=l?m.scopeParent:m;var q=y(n);q=0>q&&l&&isNaN(parseInt(n.getAttribute("tabindex"),10))?0:q;var p=l?b(m.candidates):n;0===q?l?f.push.apply(f,p):f.push(n):g.push({documentOrder:h,tabIndex:q,item:m,isScope:l,content:p})});return g.sort(aa).reduce(function(m,h){h.isScope?m.push.apply(m,h.content):m.push(h.content);return m},[]).concat(f)},H=function(a,b){b=b||{};a=b.getShadowRoot?R([a],b.includeContainer,
{filter:B.bind(null,b),flatten:!1,getShadowRoot:b.getShadowRoot,shadowRootFilter:fa}):Q(a,b.includeContainer,B.bind(null,b));return ha(a)},ia=O.concat("iframe").join(",");const I={getShadowRoot:!0};k.closestElementCrossShadowBoundary=t;k.containsCrossShadowBoundary=function(a,b){return!!U(b,f=>f===a?!0:void 0)};k.ensureId=function(a){return a?a.id=a.id||`${a.tagName.toLowerCase()}-${N()}`:""};k.filterDirectChildren=function(a,b){return Array.from(a.children).filter(f=>f.matches(b))};k.focusElement=
F;k.focusElementInGroup=(a,b,f,g=!0)=>{b=a.indexOf(b);const m=b===a.length-1;g&&(f="previous"===f&&0===b?"last":"next"===f&&m?"first":f);a="previous"===f?a[b-1]||a[g?a.length-1:b]:"next"===f?a[b+1]||a[g?0:b]:"last"===f?a[a.length-1]:a[0];F(a);return a};k.focusFirstTabbable=function(a){G(a)?.focus()};k.focusable=function(a,b){b=b||{};return b.getShadowRoot?R([a],b.includeContainer,{filter:x.bind(null,b),flatten:!0,getShadowRoot:b.getShadowRoot}):Q(a,b.includeContainer,x.bind(null,b))};k.getElementDir=
function(a){return(a=t(a,"[dir]"))?a.getAttribute("dir"):"ltr"};k.getElementWidth=function(a){return a?parseFloat(getComputedStyle(a).inlineSize):0};k.getFirstTabbable=G;k.getModeName=function(a){return t(a,`.${C.CSS_UTILITY.darkMode}, .${C.CSS_UTILITY.lightMode}`)?.classList.contains("calcite-mode-dark")?"dark":"light"};k.getShadowRootNode=function(a){a=a.getRootNode();return"host"in a?a:null};k.getSlotAssignedElements=M;k.getSlotted=function(a,b,f){b&&!Array.isArray(b)&&"string"!==typeof b&&(f=
b,b=null);b=b?Array.isArray(b)?b.map(g=>`[slot="${g}"]`).join(","):`[slot="${b}"]`:":not([slot])";return f?.all?V(a,b,f):W(a,b,f)};k.getTabIndex=y;k.getTextWidth=function(a,b){if(!a)return 0;const f=document.createElement("canvas").getContext("2d");f.font=b;return f.measureText(a).width};k.guid=N;k.intersects=function(a,b){return!(b.left>a.right||b.right<a.left||b.top>a.bottom||b.bottom<a.top)};k.isBefore=function(a,b){if(a.parentNode!==b.parentNode)return!1;const f=Array.from(a.parentNode.children);
return f.indexOf(a)<f.indexOf(b)};k.isFocusable=function(a,b){b=b||{};if(!a)throw Error("No node provided");return!1===r.call(a,ia)?!1:x(b,a)};k.isKeyboardTriggeredClick=function(a){return 0===a.detail};k.isPrimaryPointerButton=function(a){return!(!a.isPrimary||0!==a.button)};k.isTabbable=function(a,b){b=b||{};if(!a)throw Error("No node provided");return!1===r.call(a,u)?!1:B(b,a)};k.nodeListToArray=function(a){return Array.isArray(a)?a:Array.from(a)};k.queryElementRoots=D;k.setRequestedIcon=function(a,
b,f){if("string"===typeof b&&""!==b)return b;if(""===b)return a[f]};k.slotChangeGetAssignedElements=L;k.slotChangeHasAssignedElement=K;k.slotChangeHasContent=function(a){return K(a)||!!Y(a)};k.tabbable=H;k.tabbableOptions=I;k.toAriaBoolean=function(a){return(!!a).toString()};k.whenTransitionDone=async function(a,b,f,g){return Z(a,b,"transition",f,g)}});