// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.31/esri/copyright.txt for details.
//>>built
define(["exports","./debounce"],function(p,k){function u(a){if("string"==typeof a)return a;if(v(a)){for(var b=-1,e=null==a?0:a.length,f=Array(e);++b<e;)f[b]=u(a[b],b,a);return f+""}if(k.isSymbol(a))return w?w.call(a):"";b=a+"";return"0"==b&&1/a==-C?"-0":b}function D(a){return a}function x(a){return"number"==typeof a&&-1<a&&0==a%1&&9007199254740991>=a}function y(a){return k.isObjectLike(a)&&"[object Arguments]"==k.baseGetTag(a)}function E(){return!1}function F(a){return k.isObjectLike(a)&&x(a.length)&&
!!c[k.baseGetTag(a)]}function G(a){return function(b){return a(b)}}function H(a){var b;if(b=null!=a&&x(a.length))k.isObject(a)?(b=k.baseGetTag(a),b="[object Function]"==b||"[object GeneratorFunction]"==b||"[object AsyncFunction]"==b||"[object Proxy]"==b):b=!1,b=!b;if(b){b=v(a);var e=!b&&I(a),f=!b&&!e&&J(a),l=!b&&!e&&!f&&K(a);if(b=b||e||f||l){e=a.length;for(var m=String,h=-1,n=Array(e);++h<e;)n[h]=m(h);e=n}else e=[];m=e.length;for(d in a)(a=b)&&!(a="length"==d||f&&("offset"==d||"parent"==d)||l&&("buffer"==
d||"byteLength"==d||"byteOffset"==d))&&(a=d,h=m,n=typeof a,h=null==h?9007199254740991:h,a=!!h&&("number"==n||"symbol"!=n&&L.test(a))&&-1<a&&0==a%1&&a<h),a||e.push(d);var d=e}else if(k.isObject(a)){d=a&&a.constructor;d=a===("function"==typeof d&&d.prototype||M);l=[];for(f in a)("constructor"!=f||!d&&N.call(a,f))&&l.push(f);d=l}else if(d=[],null!=a)for(l in Object(a))d.push(l);return d}function z(a){return(a=null==a?"":u(a))&&O.test(a)?a.replace(A,"\\$\x26"):a}function P(a,b){return null==a?a:Q(a,"function"==
typeof b?b:D,H)}const v=Array.isArray;var C=1/0,g=k.Symbol$1?k.Symbol$1.prototype:void 0,w=g?g.toString:void 0,L=/^(?:0|[1-9]\d*)$/,M=Object.prototype;g=Object.prototype;var R=g.hasOwnProperty,S=g.propertyIsEnumerable;const I=y(function(){return arguments}())?y:function(a){return k.isObjectLike(a)&&R.call(a,"callee")&&!S.call(a,"callee")};var B=(g="object"==typeof p&&p&&!p.nodeType&&p)&&"object"==typeof module&&module&&!module.nodeType&&module;const J=((g=B&&B.exports===g?k.root$1.Buffer:void 0)?
g.isBuffer:void 0)||E;var c={};c["[object Float32Array]"]=c["[object Float64Array]"]=c["[object Int8Array]"]=c["[object Int16Array]"]=c["[object Int32Array]"]=c["[object Uint8Array]"]=c["[object Uint8ClampedArray]"]=c["[object Uint16Array]"]=c["[object Uint32Array]"]=!0;c["[object Arguments]"]=c["[object Array]"]=c["[object ArrayBuffer]"]=c["[object Boolean]"]=c["[object DataView]"]=c["[object Date]"]=c["[object Error]"]=c["[object Function]"]=c["[object Map]"]=c["[object Number]"]=c["[object Object]"]=
c["[object RegExp]"]=c["[object Set]"]=c["[object String]"]=c["[object WeakMap]"]=!1;var r=(g="object"==typeof p&&p&&!p.nodeType&&p)&&"object"==typeof module&&module&&!module.nodeType&&module,t=r&&r.exports===g&&k.freeGlobal$1.process;const K=(g=(g=function(){try{var a=r&&r.require&&r.require("util").types;return a?a:t&&t.binding&&t.binding("util")}catch(b){}}())&&g.isTypedArray)?G(g):F;var N=Object.prototype.hasOwnProperty;const Q=function(a){return function(b,e,f){var l=-1,m=Object(b);f=f(b);for(var h=
f.length;h--;){var n=f[++l];if(!1===e(m[n],n,m))break}return b}}();var A=/[\\^$.*+?()[\]{}|]/g,O=RegExp(A.source);p.escapeRegExp=z;p.filter=(a,b,e)=>{b=z(b);const f=new RegExp(b,"i");0===a.length&&console.warn("No data was passed to the filter function.\n    The data argument should be an array of objects");const l=(m,h,n)=>{if(m?.constant||m?.filterDisabled)return!0;let d=!1;P(m,(q,T)=>{"function"===typeof q||null==q||n&&!n.includes(T)||(Array.isArray(q)||"object"===typeof q&&null!==q?l(q,h)&&(d=
!0):h.test(q)&&(d=!0))});return d};return a.filter(m=>l(m,f,e))}});