// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.31/esri/copyright.txt for details.
//>>built
define(["exports","./componentsUtils","./dom","./debounce"],function(J,X,Qa,Ra){function M(a,b){return"function"===typeof a?a(b):a}function G(a){return a.split("-")[0]}function D(a){return a.split("-")[1]}function Y(a){return"x"===a?"y":"x"}function la(a){return"y"===a?"height":"width"}function P(a){return["top","bottom"].includes(G(a))?"y":"x"}function qa(a,b,c){void 0===c&&(c=!1);const d=D(a),e=Y(P(a));a=la(e);c="x"===e?d===(c?"end":"start")?"right":"left":"start"===d?"bottom":"top";b.reference[a]>
b.floating[a]&&(c=Z(c));return[c,Z(c)]}function Sa(a){const b=Z(a);return[aa(a),b,aa(b)]}function aa(a){return a.replace(/start|end/g,b=>Ta[b])}function Ua(a,b,c){const d=["left","right"],e=["right","left"],f=["top","bottom"],g=["bottom","top"];switch(a){case "top":case "bottom":return c?b?e:d:b?d:e;case "left":case "right":return b?f:g;default:return[]}}function Va(a,b,c,d){const e=D(a);a=Ua(G(a),"start"===c,d);e&&(a=a.map(f=>f+"-"+e),b&&(a=a.concat(a.map(aa))));return a}function Z(a){return a.replace(/left|right|bottom|top/g,
b=>Wa[b])}function ra(a){return"number"!==typeof a?{top:0,right:0,bottom:0,left:0,...a}:{top:a,right:a,bottom:a,left:a}}function ba(a){const {x:b,y:c,width:d,height:e}=a;return{width:d,height:e,top:c,left:b,right:b+d,bottom:c+e,x:b,y:c}}function sa(a,b,c){let {reference:d,floating:e}=a;var f=P(b);a=Y(P(b));var g=la(a),h=G(b);f="y"===f;const m=d.x+d.width/2-e.width/2,k=d.y+d.height/2-e.height/2;g=d[g]/2-e[g]/2;switch(h){case "top":h={x:m,y:d.y-e.height};break;case "bottom":h={x:m,y:d.y+d.height};break;
case "right":h={x:d.x+d.width,y:k};break;case "left":h={x:d.x-e.width,y:k};break;default:h={x:d.x,y:d.y}}switch(D(b)){case "start":h[a]-=g*(c&&f?-1:1);break;case "end":h[a]+=g*(c&&f?-1:1)}return h}async function T(a,b){var c;void 0===b&&(b={});const {x:d,y:e,platform:f,rects:g,elements:h,strategy:m}=a,{boundary:k="clippingAncestors",rootBoundary:q="viewport",elementContext:t="floating",altBoundary:u=!1,padding:v=0}=M(b,a);a=ra(v);var l=h[u?"floating"===t?"reference":"floating":t];b=ba(await f.getClippingRect({element:(null!=
(c=await (null==f.isElement?void 0:f.isElement(l)))?c:1)?l:l.contextElement||await (null==f.getDocumentElement?void 0:f.getDocumentElement(h.floating)),boundary:k,rootBoundary:q,strategy:m}));l="floating"===t?{x:d,y:e,width:g.floating.width,height:g.floating.height}:g.reference;const p=await (null==f.getOffsetParent?void 0:f.getOffsetParent(h.floating));c=await (null==f.isElement?void 0:f.isElement(p))?await (null==f.getScale?void 0:f.getScale(p))||{x:1,y:1}:{x:1,y:1};l=ba(f.convertOffsetParentRelativeRectToViewportRelativeRect?
await f.convertOffsetParentRelativeRectToViewportRelativeRect({elements:h,rect:l,offsetParent:p,strategy:m}):l);return{top:(b.top-l.top+a.top)/c.y,bottom:(l.bottom-b.bottom+a.bottom)/c.y,left:(b.left-l.left+a.left)/c.x,right:(l.right-b.right+a.right)/c.x}}function Xa(a,b,c){return(a?[...c.filter(d=>D(d)===a),...c.filter(d=>D(d)!==a)]:c.filter(d=>G(d)===d)).filter(d=>a?D(d)===a||(b?aa(d)!==d:!1):!0)}function ta(a,b){return{top:a.top-b.height,right:a.right-b.width,bottom:a.bottom-b.height,left:a.left-
b.width}}function ua(a){return va.some(b=>0<=a[b])}async function Ya(a,b){const {placement:c,platform:d,elements:e}=a;var f=await (null==d.isRTL?void 0:d.isRTL(e.floating)),g=G(c);const h=D(c),m="y"===P(c);g=["left","top"].includes(g)?-1:1;f=f&&m?-1:1;a=M(b,a);let {mainAxis:k,crossAxis:q,alignmentAxis:t}="number"===typeof a?{mainAxis:a,crossAxis:0,alignmentAxis:null}:{mainAxis:0,crossAxis:0,alignmentAxis:null,...a};h&&"number"===typeof t&&(q="end"===h?-1*t:t);return m?{x:q*f,y:k*g}:{x:k*g,y:q*f}}
function ca(){return"undefined"!==typeof window}function Q(a){return wa(a)?(a.nodeName||"").toLowerCase():"#document"}function A(a){var b;return(null==a||null==(b=a.ownerDocument)?void 0:b.defaultView)||window}function H(a){var b;return null==(b=(wa(a)?a.ownerDocument:a.document)||window.document)?void 0:b.documentElement}function wa(a){return ca()?a instanceof Node||a instanceof A(a).Node:!1}function C(a){return ca()?a instanceof Element||a instanceof A(a).Element:!1}function E(a){return ca()?a instanceof
HTMLElement||a instanceof A(a).HTMLElement:!1}function xa(a){return ca()&&"undefined"!==typeof ShadowRoot?a instanceof ShadowRoot||a instanceof A(a).ShadowRoot:!1}function U(a){const {overflow:b,overflowX:c,overflowY:d,display:e}=B(a);return/auto|scroll|overlay|hidden|clip/.test(b+d+c)&&!["inline","contents"].includes(e)}function da(a){return[":popover-open",":modal"].some(b=>{try{return a.matches(b)}catch(c){return!1}})}function ea(a){const b=ma(),c=C(a)?B(a):a;return"none"!==c.transform||"none"!==
c.perspective||(c.containerType?"normal"!==c.containerType:!1)||!b&&(c.backdropFilter?"none"!==c.backdropFilter:!1)||!b&&(c.filter?"none"!==c.filter:!1)||["transform","perspective","filter"].some(d=>(c.willChange||"").includes(d))||["paint","layout","strict","content"].some(d=>(c.contain||"").includes(d))}function ma(){return"undefined"!==typeof CSS&&CSS.supports?CSS.supports("-webkit-backdrop-filter","none"):!1}function R(a){return["html","body","#document"].includes(Q(a))}function B(a){return A(a).getComputedStyle(a)}
function fa(a){return C(a)?{scrollLeft:a.scrollLeft,scrollTop:a.scrollTop}:{scrollLeft:a.scrollX,scrollTop:a.scrollY}}function K(a){if("html"===Q(a))return a;a=a.assignedSlot||a.parentNode||xa(a)&&a.host||H(a);return xa(a)?a.host:a}function ya(a){const b=K(a);return R(b)?a.ownerDocument?a.ownerDocument.body:a.body:E(b)&&U(b)?b:ya(b)}function V(a,b,c){var d;void 0===b&&(b=[]);void 0===c&&(c=!0);const e=ya(a);a=e===(null==(d=a.ownerDocument)?void 0:d.body);d=A(e);return a?(a=d.parent&&Object.getPrototypeOf(d.parent)?
d.frameElement:null,b.concat(d,d.visualViewport||[],U(e)?e:[],a&&c?V(a):[])):b.concat(e,V(e,[],c))}function za(a){var b=B(a);let c=parseFloat(b.width)||0;b=parseFloat(b.height)||0;var d=E(a);const e=d?a.offsetWidth:c;a=d?a.offsetHeight:b;if(d=ha(c)!==e||ha(b)!==a)c=e,b=a;return{width:c,height:b,$:d}}function na(a){return C(a)?a:a.contextElement}function S(a){var b=na(a);if(!E(b))return{x:1,y:1};a=b.getBoundingClientRect();const {width:c,height:d,$:e}=za(b);b=(e?ha(a.width):a.width)/c;a=(e?ha(a.height):
a.height)/d;b&&Number.isFinite(b)||(b=1);a&&Number.isFinite(a)||(a=1);return{x:b,y:a}}function Aa(a){a=A(a);return ma()&&a.visualViewport?{x:a.visualViewport.offsetLeft,y:a.visualViewport.offsetTop}:Za}function N(a,b,c,d){void 0===b&&(b=!1);void 0===c&&(c=!1);var e=a.getBoundingClientRect(),f=na(a),g={x:1,y:1};b&&(d?C(d)&&(g=S(d)):g=S(a));a=c;void 0===a&&(a=!1);a=!d||a&&d!==A(f)?!1:a;b=a?Aa(f):{x:0,y:0};a=(e.left+b.x)/g.x;b=(e.top+b.y)/g.y;c=e.width/g.x;e=e.height/g.y;if(f){g=A(f);f=d&&C(d)?A(d):
d;var h=g;for(g=h.frameElement;g&&d&&f!==h;){h=S(g);var m=g.getBoundingClientRect();const k=B(g),q=m.left+(g.clientLeft+parseFloat(k.paddingLeft))*h.x;m=m.top+(g.clientTop+parseFloat(k.paddingTop))*h.y;a*=h.x;b*=h.y;c*=h.x;e*=h.y;a+=q;b+=m;h=A(g);g=h.frameElement}}return ba({width:c,height:e,x:a,y:b})}function Ba(a){return N(H(a)).left+fa(a).scrollLeft}function Ca(a,b,c){if("viewport"===b){b=A(a);var d=H(a);b=b.visualViewport;a=d.clientWidth;d=d.clientHeight;var e=0,f=0;if(b){a=b.width;d=b.height;
const g=ma();if(!g||g&&"fixed"===c)e=b.offsetLeft,f=b.offsetTop}c={width:a,height:d,x:e,y:f}}else"document"===b?(f=H(a),c=H(f),e=fa(f),b=f.ownerDocument.body,a=I(c.scrollWidth,c.clientWidth,b.scrollWidth,b.clientWidth),d=I(c.scrollHeight,c.clientHeight,b.scrollHeight,b.clientHeight),f=-e.scrollLeft+Ba(f),e=-e.scrollTop,"rtl"===B(b).direction&&(f+=I(c.clientWidth,b.clientWidth)-a),c={width:a,height:d,x:f,y:e}):C(b)?(a=N(b,!0,"fixed"===c),c=a.top+b.clientTop,a=a.left+b.clientLeft,d=E(b)?S(b):{x:1,y:1},
c={width:b.clientWidth*d.x,height:b.clientHeight*d.y,x:a*d.x,y:c*d.y}):(c=Aa(a),c={...b,x:b.x-c.x,y:b.y-c.y});return ba(c)}function Da(a,b){a=K(a);return a===b||!C(a)||R(a)?!1:"fixed"===B(a).position||Da(a,b)}function $a(a,b){var c=b.get(a);if(c)return c;c=V(a,[],!1).filter(g=>C(g)&&"body"!==Q(g));let d=null;const e="fixed"===B(a).position;let f=e?K(a):a;for(;C(f)&&!R(f);){const g=B(f),h=ea(f);h||"fixed"!==g.position||(d=null);(e?!h&&!d:!h&&"static"===g.position&&d&&["absolute","fixed"].includes(d.position)||
U(f)&&!h&&Da(a,f))?c=c.filter(m=>m!==f):d=g;f=K(f)}b.set(a,c);return c}function Ea(a,b){return E(a)&&"fixed"!==B(a).position?b?b(a):a.offsetParent:null}function Fa(a,b){const c=A(a);if(da(a))return c;if(!E(a)){for(a=K(a);a&&!R(a);){if(C(a)&&"static"!==B(a).position)return a;a=K(a)}return c}let d=Ea(a,b);for(;d&&["table","td","th"].includes(Q(d))&&"static"===B(d).position;)d=Ea(d,b);if(d&&R(d)&&"static"===B(d).position&&!ea(d))return c;if(!(b=d))a:{for(a=K(a);E(a)&&!R(a);){if(ea(a)){b=a;break a}else if(da(a)){b=
null;break a}a=K(a)}b=null}return b||c}function ab(a,b){function c(){var h;clearTimeout(f);null==(h=e)||h.disconnect();e=null}function d(h,m){function k(r){r=r[0].intersectionRatio;if(r!==m){if(!n)return d();r?d(!1,r):f=setTimeout(()=>{d(!1,1E-7)},1E3)}n=!1}void 0===h&&(h=!1);void 0===m&&(m=1);c();const {left:q,top:t,width:u,height:v}=a.getBoundingClientRect();h||b();if(u&&v){h=ia(t);var l=ia(g.clientWidth-(q+u)),p=ia(g.clientHeight-(t+v)),w=ia(q);h={rootMargin:-h+"px "+-l+"px "+-p+"px "+-w+"px",
threshold:I(0,L(1,m))||1};var n=!0;try{e=new IntersectionObserver(k,{...h,root:g.ownerDocument})}catch(r){e=new IntersectionObserver(k,h)}e.observe(a)}}let e=null,f;const g=H(a);d(!0);return c}function bb(a,b,c,d){function e(){const n=N(a);!w||n.x===w.x&&n.y===w.y&&n.width===w.width&&n.height===w.height||c();w=n;p=requestAnimationFrame(e)}void 0===d&&(d={});const {ancestorScroll:f=!0,ancestorResize:g=!0,elementResize:h="function"===typeof ResizeObserver,layoutShift:m="function"===typeof IntersectionObserver,
animationFrame:k=!1}=d,q=na(a),t=f||g?[...(q?V(q):[]),...V(b)]:[];t.forEach(n=>{f&&n.addEventListener("scroll",c,{passive:!0});g&&n.addEventListener("resize",c)});const u=q&&m?ab(q,c):null;let v=-1,l=null;h&&(l=new ResizeObserver(n=>{[n]=n;n&&n.target===q&&l&&(l.unobserve(b),cancelAnimationFrame(v),v=requestAnimationFrame(()=>{var r;null==(r=l)||r.observe(b)}));c()}),q&&!k&&l.observe(q),l.observe(b));let p,w=k?N(a):null;k&&e();c();return()=>{var n;t.forEach(r=>{f&&r.removeEventListener("scroll",c);
g&&r.removeEventListener("resize",c)});null==u||u();null==(n=l)||n.disconnect();l=null;k&&cancelAnimationFrame(p)}}function cb(a){a:{for(var b=a;b;b=oa(b))if(b instanceof Element&&"none"===getComputedStyle(b).display){a=null;break a}for(a=oa(a);a;a=oa(a))if(a instanceof Element&&(b=getComputedStyle(a),"contents"!==b.display&&("static"!==b.position||ea(b)||"BODY"===a.tagName)))break a;a=null}return a}function oa(a){return a.assignedSlot?a.assignedSlot:a.parentNode instanceof ShadowRoot?a.parentNode.host:
a.parentNode}function Ga(a){const b=window.devicePixelRatio||1;return Math.round(a*b)/b}function db({placement:a,flipDisabled:b,flipPlacements:c,offsetDistance:d,offsetSkidding:e,arrowEl:f,type:g}){const h=[eb(),fb()];return"menu"===g?[...h,Ha({fallbackPlacements:c||"top-start top top-end bottom-start bottom bottom-end".split(" ")})]:"popover"===g||"tooltip"===g?(d=[...h,gb({mainAxis:"number"===typeof d?d:0,crossAxis:"number"===typeof e?e:0})],"auto"===a||"auto-start"===a||"auto-end"===a?d.push(hb({alignment:"auto-start"===
a?"start":"auto-end"===a?"end":null})):b||d.push(Ha(c?{fallbackPlacements:c}:{})),f&&d.push(ib({element:f})),d):[]}function Ia(a,b=!1){const c=["left","right"];b&&c.reverse();return a.replace(/leading/gi,c[0]).replace(/trailing/gi,c[1])}async function Ja(a,b,c){if(c.isConnected){var d=X.isBrowser()?bb:(f,g,h)=>{h();return()=>{}};W.set(a,{state:"pending"});var e;b=d(b,c,()=>{const f=a.reposition();e||=f});W.set(a,{state:"active",cleanUp:b});return e}}function Ka(a,b,c){c&&b&&(b=W.get(a),"active"===
b?.state&&b.cleanUp(),W.delete(a),ja.get(a)?.cancel(),ja.delete(a))}const va=["top","right","bottom","left"],La=["start","end"],Ma=va.reduce((a,b)=>a.concat(b,b+"-"+La[0],b+"-"+La[1]),[]),L=Math.min,I=Math.max,ha=Math.round,ia=Math.floor,Wa={left:"right",right:"left",bottom:"top",top:"bottom"},Ta={start:"end",end:"start"},jb=async(a,b,c)=>{const {placement:d="bottom",strategy:e="absolute",middleware:f=[],platform:g}=c;c=f.filter(Boolean);const h=await (null==g.isRTL?void 0:g.isRTL(b));let m=await g.getElementRects({reference:a,
floating:b,strategy:e}),{x:k,y:q}=sa(m,d,h),t=d,u={},v=0;for(let l=0;l<c.length;l++){const {name:p,fn:w}=c[l],{x:n,y:r,data:x,reset:y}=await w({x:k,y:q,initialPlacement:d,placement:t,strategy:e,middlewareData:u,rects:m,platform:g,elements:{reference:a,floating:b}});k=null!=n?n:k;q=null!=r?r:q;u={...u,[p]:{...u[p],...x}};y&&50>=v&&(v++,"object"===typeof y&&(y.placement&&(t=y.placement),y.rects&&(m=!0===y.rects?await g.getElementRects({reference:a,floating:b,strategy:e}):y.rects),{x:k,y:q}=sa(m,t,h)),
l=-1)}return{x:k,y:q,placement:t,strategy:e,middlewareData:u}},Za={x:0,y:0},pa={convertOffsetParentRelativeRectToViewportRelativeRect:function(a){let {elements:b,rect:c,offsetParent:d,strategy:e}=a;a="fixed"===e;const f=H(d);var g=b?da(b.floating):!1;if(d===f||g&&a)return c;g={scrollLeft:0,scrollTop:0};let h={x:1,y:1};var m=0,k=0;const q=E(d);if(q||!q&&!a){if("body"!==Q(d)||U(f))g=fa(d);E(d)&&(a=N(d),h=S(d),m=a.x+d.clientLeft,k=a.y+d.clientTop)}return{width:c.width*h.x,height:c.height*h.y,x:c.x*h.x-
g.scrollLeft*h.x+m,y:c.y*h.y-g.scrollTop*h.y+k}},getDocumentElement:H,getClippingRect:function(a){let {element:b,boundary:c,rootBoundary:d,strategy:e}=a;a=[...("clippingAncestors"===c?da(b)?[]:$a(b,this._c):[].concat(c)),d];a=a.reduce((f,g)=>{g=Ca(b,g,e);f.top=I(g.top,f.top);f.right=L(g.right,f.right);f.bottom=L(g.bottom,f.bottom);f.left=I(g.left,f.left);return f},Ca(b,a[0],e));return{width:a.right-a.left,height:a.bottom-a.top,x:a.left,y:a.top}},getOffsetParent:Fa,getElementRects:async function(a){var b=
this.getOffsetParent||Fa,c=this.getDimensions;c=await c(a.floating);var d=a.reference;b=await b(a.floating);var e=a.strategy;a=E(b);const f=H(b);e="fixed"===e;d=N(d,!0,e,b);let g={scrollLeft:0,scrollTop:0};var h=0,m=0;if(a||!a&&!e){if("body"!==Q(b)||U(f))g=fa(b);a?(a=N(b,!0,e,b),h=a.x+b.clientLeft,m=a.y+b.clientTop):f&&(h=Ba(f))}return{reference:{x:d.left+g.scrollLeft-h,y:d.top+g.scrollTop-m,width:d.width,height:d.height},floating:{x:0,y:0,width:c.width,height:c.height}}},getClientRects:function(a){return Array.from(a.getClientRects())},
getDimensions:function(a){const {width:b,height:c}=za(a);return{width:b,height:c}},getScale:S,isElement:C,isRTL:function(a){return"rtl"===B(a).direction}},gb=function(a){void 0===a&&(a=0);return{name:"offset",options:a,async fn(b){var c,d;const {x:e,y:f,placement:g,middlewareData:h}=b;b=await Ya(b,a);return g===(null==(c=h.offset)?void 0:c.placement)&&null!=(d=h.arrow)&&d.alignmentOffset?{}:{x:e+b.x,y:f+b.y,data:{...b,placement:g}}}}},hb=function(a){void 0===a&&(a={});return{name:"autoPlacement",
options:a,async fn(b){var c,d,e;const {rects:f,middlewareData:g,placement:h,platform:m,elements:k}=b,{crossAxis:q=!1,alignment:t,allowedPlacements:u=Ma,autoAlignment:v=!0,...l}=M(a,b);var p=void 0!==t||u===Ma?Xa(t||null,v,u):u,w=await T(b,l);b=(null==(c=g.autoPlacement)?void 0:c.index)||0;c=p[b];if(null==c)return{};var n=qa(c,f,await (null==m.isRTL?void 0:m.isRTL(k.floating)));if(h!==c)return{reset:{placement:p[0]}};n=[w[G(c)],w[n[0]],w[n[1]]];w=[...((null==(d=g.autoPlacement)?void 0:d.overflows)||
[]),{placement:c,overflows:n}];if(d=p[b+1])return{data:{index:b+1,overflows:w},reset:{placement:d}};d=w.map(r=>{const x=D(r.placement);return[r.placement,x&&q?r.overflows.slice(0,2).reduce((y,z)=>y+z,0):r.overflows[0],r.overflows]}).sort((r,x)=>r[1]-x[1]);p=(null==(e=d.filter(r=>r[2].slice(0,D(r[0])?2:3).every(x=>0>=x))[0])?void 0:e[0])||d[0][0];return p!==h?{data:{index:b+1,overflows:w},reset:{placement:p}}:{}}}},eb=function(a){void 0===a&&(a={});return{name:"shift",options:a,async fn(b){const {x:c,
y:d,placement:e}=b,{mainAxis:f=!0,crossAxis:g=!1,limiter:h={fn:l=>{let {x:p,y:w}=l;return{x:p,y:w}}},...m}=M(a,b);var k={x:c,y:d};const q=await T(b,m),t=P(G(e)),u=Y(t);let v=k[u];k=k[t];f&&(v=I(v+q["y"===u?"top":"left"],L(v,v-q["y"===u?"bottom":"right"])));g&&(k=I(k+q["y"===t?"top":"left"],L(k,k-q["y"===t?"bottom":"right"])));b=h.fn({...b,[u]:v,[t]:k});return{...b,data:{x:b.x-c,y:b.y-d}}}}},Ha=function(a){void 0===a&&(a={});return{name:"flip",options:a,async fn(b){var c,d;const {placement:e,middlewareData:f,
rects:g,initialPlacement:h,platform:m,elements:k}=b,{mainAxis:q=!0,crossAxis:t=!0,fallbackPlacements:u,fallbackStrategy:v="bestFit",fallbackAxisSideDirection:l="none",flipAlignment:p=!0,...w}=M(a,b);if(null!=(c=f.arrow)&&c.alignmentOffset)return{};c=G(e);var n=G(h)===h;const r=await (null==m.isRTL?void 0:m.isRTL(k.floating));n=u||(n||!p?[Z(h)]:Sa(h));u||"none"===l||n.push(...Va(h,p,l,r));n=[h,...n];const x=await T(b,w),y=[];b=(null==(d=f.flip)?void 0:d.overflows)||[];q&&y.push(x[c]);t&&(d=qa(e,g,
r),y.push(x[d[0]],x[d[1]]));b=[...b,{placement:e,overflows:y}];if(!y.every(F=>0>=F)){var z,ka;d=((null==(z=f.flip)?void 0:z.index)||0)+1;if(z=n[d])return{data:{index:d,overflows:b},reset:{placement:z}};z=null==(ka=b.filter(F=>0>=F.overflows[0]).sort((F,O)=>F.overflows[1]-O.overflows[1])[0])?void 0:ka.placement;if(!z)switch(v){case "bestFit":var Na;(ka=null==(Na=b.map(F=>[F.placement,F.overflows.filter(O=>0<O).reduce((O,kb)=>O+kb,0)]).sort((F,O)=>F[1]-O[1])[0])?void 0:Na[0])&&(z=ka);break;case "initialPlacement":z=
h}if(e!==z)return{reset:{placement:z}}}return{}}}},fb=function(a){void 0===a&&(a={});return{name:"hide",options:a,async fn(b){var {rects:c}=b;const {strategy:d="referenceHidden",...e}=M(a,b);switch(d){case "referenceHidden":return b=await T(b,{...e,elementContext:"reference"}),c=ta(b,c.reference),{data:{referenceHiddenOffsets:c,referenceHidden:ua(c)}};case "escaped":return b=await T(b,{...e,altBoundary:!0}),c=ta(b,c.floating),{data:{escapedOffsets:c,escaped:ua(c)}};default:return{}}}}},ib=a=>({name:"arrow",
options:a,async fn(b){const {x:c,y:d,placement:e,rects:f,platform:g,elements:h,middlewareData:m}=b,{element:k,padding:q=0}=M(a,b)||{};if(null==k)return{};var t=ra(q);b={x:c,y:d};const u=Y(P(e));var v=la(u),l=await g.getDimensions(k),p="y"===u,w=p?"top":"left",n=p?"bottom":"right",r=p?"clientHeight":"clientWidth",x=f.reference[v]+f.reference[u]-b[u]-f.floating[v];const y=b[u]-f.reference[u],z=await (null==g.getOffsetParent?void 0:g.getOffsetParent(k));(p=z?z[r]:0)&&await (null==g.isElement?void 0:
g.isElement(z))||(p=h.floating[r]||f.floating[v]);r=x/2-y/2;x=p/2-l[v]/2-1;w=L(t[w],x);n=L(t[n],x);t=p-l[v]-n;p=p/2-l[v]/2+r;r=I(w,L(p,t));l=(v=!m.arrow&&null!=D(e)&&p!==r&&0>f.reference[v]/2-(p<w?w:n)-l[v]/2)?p<w?p-w:p-t:0;return{[u]:b[u]+l,data:{[u]:r,centerOffset:p-r-l,...(v&&{alignmentOffset:l})},reset:v}}}),lb=(a,b,c)=>{const d=new Map;c={platform:pa,...c};return jb(a,b,{...c,platform:{...c.platform,_c:d}})};(function(){if(X.isBrowser()){const a=pa.getOffsetParent;pa.getOffsetParent=b=>a(b,cb)}})();
const Oa=async(a,{referenceEl:b,floatingEl:c,overlayPositioning:d="absolute",placement:e,flipDisabled:f,flipPlacements:g,offsetDistance:h,offsetSkidding:m,arrowEl:k,type:q})=>{if(!b||!c)return null;const t="rtl"===Qa.getElementDir(c),{x:u,y:v,placement:l,strategy:p,middlewareData:w}=await lb(b,c,{strategy:d,placement:"auto"===e||"auto-start"===e||"auto-end"===e?void 0:Ia(e,t),middleware:db({placement:e,flipDisabled:f,flipPlacements:g?.map(n=>Ia(n,t)),offsetDistance:h,offsetSkidding:m,arrowEl:k,type:q})});
if(k&&w.arrow){const {x:n,y:r}=w.arrow;b=l.split("-")[0];d=null!=n?"left":"top";e=mb[b];"floatingLayout"in a&&(a.floatingLayout="left"===b||"right"===b?"horizontal":"vertical");Object.assign(k.style,{left:"",top:"",bottom:"",right:"",[d]:`${"left"==d?n:r}px`,[b]:"100%",transform:e})}b=(k=w.hide?.referenceHidden?"hidden":null)?"none":null;c.setAttribute("data-placement",l);({open:a}=a);Object.assign(c.style,{visibility:k,pointerEvents:b,position:p,transform:a?`translate(${Ga(u)}px,${Ga(v)}px)`:"",
top:0,left:0})},Pa="top bottom right left top-start top-end bottom-start bottom-end right-start right-end left-start left-end leading trailing leading-start leading-end trailing-start trailing-end".split(" "),mb={top:"",left:"rotate(-90deg)",bottom:"rotate(180deg)",right:"rotate(90deg)"},W=new WeakMap,ja=new WeakMap,nb=Math.ceil(Math.hypot(4,4));J.FloatingCSS={animation:"calcite-floating-ui-anim",animationActive:"calcite-floating-ui-anim--active",arrow:"calcite-floating-ui-arrow",arrowStroke:"calcite-floating-ui-arrow__stroke"};
J.connectFloatingUI=async function(a,b,c){if(c&&b&&(Ka(a,b,c),Object.assign(c.style,{visibility:"hidden",pointerEvents:"none",position:a.overlayPositioning}),a.open))return Ja(a,b,c)};J.defaultEndMenuPlacement="bottom-end";J.defaultMenuPlacement="bottom-start";J.defaultOffsetDistance=nb;J.disconnectFloatingUI=Ka;J.filterValidFlipPlacements=function(a,b){const c=a.filter(d=>Pa.includes(d));c.length!==a.length&&console.warn(`${b.tagName}: Invalid value found in: flipPlacements. Try any of these: ${Pa.map(d=>
`"${d}"`).join(", ").trim()}`,{el:b});return c};J.reposition=async function(a,b,c=!1){if(a.open&&b.floatingEl&&b.referenceEl){if(!W.get(a))return Ja(a,b.referenceEl,b.floatingEl);c?(c=ja.get(a),c||(c=Ra.debounce(Oa,X.DEBOUNCE.reposition,{leading:!0,maxWait:X.DEBOUNCE.reposition}),ja.set(a,c))):c=Oa;await c(a,b)}}});