// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.31/esri/copyright.txt for details.
//>>built
define(["exports","./dom","./componentsUtils"],function(I,m,fa){function Q(c,f){var e=Object.keys(c);if(Object.getOwnPropertySymbols){var k=Object.getOwnPropertySymbols(c);f&&(k=k.filter(function(h){return Object.getOwnPropertyDescriptor(c,h).enumerable}));e.push.apply(e,k)}return e}function R(c){for(var f=1;f<arguments.length;f++){var e=null!=arguments[f]?arguments[f]:{};f%2?Q(Object(e),!0).forEach(function(k){var h,z=e[k];a:if("object"==typeof k&&k){var q=k[Symbol.toPrimitive];if(void 0!==q){k=
q.call(k,"string");if("object"!=typeof k)break a;throw new TypeError("@@toPrimitive must return a primitive value.");}k=String(k)}(h="symbol"==typeof k?k:k+"")in c?Object.defineProperty(c,h,{value:z,enumerable:!0,configurable:!0,writable:!0}):c[h]=z}):Object.getOwnPropertyDescriptors?Object.defineProperties(c,Object.getOwnPropertyDescriptors(e)):Q(Object(e)).forEach(function(k){Object.defineProperty(c,k,Object.getOwnPropertyDescriptor(e,k))})}return c}var S={activateTrap:function(c,f){if(0<c.length){var e=
c[c.length-1];e!==f&&e.pause()}e=c.indexOf(f);-1!==e&&c.splice(e,1);c.push(f)},deactivateTrap:function(c,f){f=c.indexOf(f);-1!==f&&c.splice(f,1);0<c.length&&c[c.length-1].unpause()}},B=function(c){return"Tab"===(null===c||void 0===c?void 0:c.key)||9===(null===c||void 0===c?void 0:c.keyCode)},ha=function(c){return B(c)&&!c.shiftKey},ia=function(c){return B(c)&&c.shiftKey},T=function(c,f){var e=-1;c.every(function(k,h){return f(k)?(e=h,!1):!0});return e},C=function(c){for(var f=arguments.length,e=Array(1<
f?f-1:0),k=1;k<f;k++)e[k-1]=arguments[k];return"function"===typeof c?c.apply(void 0,e):c},J=function(c){return c.target.shadowRoot&&"function"===typeof c.composedPath?c.composedPath()[0]:c.target},ja=[],ma=function(c,f){var e=(null===f||void 0===f?void 0:f.document)||document,k=(null===f||void 0===f?void 0:f.trapStack)||ja,h=R({returnFocusOnDeactivate:!0,escapeDeactivates:!0,delayInitialFocus:!0,isKeyForward:ha,isKeyBackward:ia},f),z=[],q=[],n=[],M=null,u=null,r=!1,w=!1,N=void 0,K=void 0,t=function(a,
b,d){return a&&void 0!==a[b]?a[b]:h[d||b]},A=function(a,b){var d="function"===typeof(null===b||void 0===b?void 0:b.composedPath)?b.composedPath():void 0;return q.findIndex(function(g){var l=g.container;g=g.tabbableNodes;return l.contains(a)||(null===d||void 0===d?void 0:d.includes(l))||g.find(function(p){return p===a})})},D=function(a){var b=h[a];if("function"===typeof b){for(var d=arguments.length,g=Array(1<d?d-1:0),l=1;l<d;l++)g[l-1]=arguments[l];b=b.apply(void 0,g)}!0===b&&(b=void 0);if(!b){if(void 0===
b||!1===b)return b;throw Error("`".concat(a,"` was specified but was not a node, or did not return a node"));}d=b;if("string"===typeof b&&(d=e.querySelector(b),!d))throw Error("`".concat(a,"` as selector refers to no known node"));return d},E=function(){var a=D("initialFocus");if(!1===a)return!1;void 0!==a&&m.isFocusable(a,h.tabbableOptions)||(a=0<=A(e.activeElement)?e.activeElement:(a=n[0])&&a.firstTabbableNode||D("fallbackFocus"));if(!a)throw Error("Your focus-trap needs to have at least one focusable element");
return a},G=function(){q=z.map(function(a){var b=m.tabbable(a,h.tabbableOptions),d=m.focusable(a,h.tabbableOptions),g=0<b.length?b[0]:void 0,l=0<b.length?b[b.length-1]:void 0,p=d.find(function(v){return m.isTabbable(v)}),F=d.slice().reverse().find(function(v){return m.isTabbable(v)}),ka=!!b.find(function(v){return 0<m.getTabIndex(v)});return{container:a,tabbableNodes:b,focusableNodes:d,posTabIndexesFound:ka,firstTabbableNode:g,lastTabbableNode:l,firstDomTabbableNode:p,lastDomTabbableNode:F,nextTabbableNode:function(v){var U=
1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0,V=b.indexOf(v);return 0>V?U?d.slice(d.indexOf(v)+1).find(function(O){return m.isTabbable(O)}):d.slice(0,d.indexOf(v)).reverse().find(function(O){return m.isTabbable(O)}):b[V+(U?1:-1)]}}});n=q.filter(function(a){return 0<a.tabbableNodes.length});if(0>=n.length&&!D("fallbackFocus"))throw Error("Your focus-trap must have at least one container with at least one tabbable node in it at all times");if(q.find(function(a){return a.posTabIndexesFound})&&
1<q.length)throw Error("At least one node with a positive tabindex was found in one of your focus-trap's multiple containers. Positive tabindexes are only supported in single-container focus-traps.");},W=function(a){if(a=a.activeElement)return a.shadowRoot&&null!==a.shadowRoot.activeElement?W(a.shadowRoot):a},x=function(a){!1!==a&&a!==W(document)&&(a&&a.focus?(a.focus({preventScroll:!!h.preventScroll}),u=a,a.tagName&&"input"===a.tagName.toLowerCase()&&"function"===typeof a.select&&a.select()):x(E()))},
X=function(a){var b=D("setReturnFocus",a);return b?b:!1===b?!1:a},Y=function(a){var b=a.target,d=a.event;a=a.isBackward;var g=void 0===a?!1:a;b=b||J(d);G();a=null;if(0<n.length){var l=A(b,d),p=0<=l?q[l]:void 0;0>l?a=g?n[n.length-1].lastTabbableNode:n[0].firstTabbableNode:g?(g=T(n,function(F){return b===F.firstTabbableNode}),0>g&&(p.container===b||m.isFocusable(b,h.tabbableOptions)&&!m.isTabbable(b,h.tabbableOptions)&&!p.nextTabbableNode(b,!1))&&(g=l),0<=g?(d=n[0===g?n.length-1:g-1],a=0<=m.getTabIndex(b)?
d.lastTabbableNode:d.lastDomTabbableNode):B(d)||(a=p.nextTabbableNode(b,!1))):(g=T(n,function(F){return b===F.lastTabbableNode}),0>g&&(p.container===b||m.isFocusable(b,h.tabbableOptions)&&!m.isTabbable(b,h.tabbableOptions)&&!p.nextTabbableNode(b))&&(g=l),0<=g?(d=n[g===n.length-1?0:g+1],a=0<=m.getTabIndex(b)?d.firstTabbableNode:d.firstDomTabbableNode):B(d)||(a=p.nextTabbableNode(b)))}else a=D("fallbackFocus");return a},L=function(a){var b=J(a);0<=A(b,a)||(C(h.clickOutsideDeactivates,a)?y.deactivate({returnFocus:h.returnFocusOnDeactivate}):
C(h.allowOutsideClick,a)||a.preventDefault())},Z=function(a){var b=J(a),d=0<=A(b,a);if(d||b instanceof Document)d&&(u=b);else{a.stopImmediatePropagation();a=!0;if(u)if(0<m.getTabIndex(u)){if(b=A(u),b=q[b].tabbableNodes,0<b.length&&(d=b.findIndex(function(l){return l===u}),0<=d))if(h.isKeyForward(K)){if(d+1<b.length){var g=b[d+1];a=!1}}else 0<=d-1&&(g=b[d-1],a=!1)}else q.some(function(l){return l.tabbableNodes.some(function(p){return 0<m.getTabIndex(p)})})||(a=!1);else a=!1;a&&(g=Y({target:u,isBackward:h.isKeyBackward(K)}));
g?x(g):x(u||E())}K=void 0},la=function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1;K=a;if(b=Y({event:a,isBackward:b}))B(a)&&a.preventDefault(),x(b)},aa=function(a){(h.isKeyForward(a)||h.isKeyBackward(a))&&la(a,h.isKeyBackward(a))},ba=function(a){"Escape"!==(null===a||void 0===a?void 0:a.key)&&"Esc"!==(null===a||void 0===a?void 0:a.key)&&27!==(null===a||void 0===a?void 0:a.keyCode)||!1===C(h.escapeDeactivates,a)||(a.preventDefault(),y.deactivate())},ca=function(a){var b=J(a);
0<=A(b,a)||C(h.clickOutsideDeactivates,a)||C(h.allowOutsideClick,a)||(a.preventDefault(),a.stopImmediatePropagation())},da=function(){if(r)return S.activateTrap(k,y),N=h.delayInitialFocus?setTimeout(function(){x(E())},0):x(E()),e.addEventListener("focusin",Z,!0),e.addEventListener("mousedown",L,{capture:!0,passive:!1}),e.addEventListener("touchstart",L,{capture:!0,passive:!1}),e.addEventListener("click",ca,{capture:!0,passive:!1}),e.addEventListener("keydown",aa,{capture:!0,passive:!1}),e.addEventListener("keydown",
ba),y},ea=function(){if(r)return e.removeEventListener("focusin",Z,!0),e.removeEventListener("mousedown",L,!0),e.removeEventListener("touchstart",L,!0),e.removeEventListener("click",ca,!0),e.removeEventListener("keydown",aa,!0),e.removeEventListener("keydown",ba),y};f=function(a){a.some(function(b){return Array.from(b.removedNodes).some(function(d){return d===u})})&&x(E())};var P="undefined"!==typeof window&&"MutationObserver"in window?new MutationObserver(f):void 0,H=function(){P&&(P.disconnect(),
r&&!w&&z.map(function(a){P.observe(a,{subtree:!0,childList:!0})}))};var y={get active(){return r},get paused(){return w},activate:function(a){if(r)return this;var b=t(a,"onActivate"),d=t(a,"onPostActivate"),g=t(a,"checkCanFocusTrap");g||G();r=!0;w=!1;M=e.activeElement;null===b||void 0===b||b();a=function(){g&&G();da();H();null===d||void 0===d||d()};if(g)return g(z.concat()).then(a,a),this;a();return this},deactivate:function(a){if(!r)return this;var b=R({onDeactivate:h.onDeactivate,onPostDeactivate:h.onPostDeactivate,
checkCanReturnFocus:h.checkCanReturnFocus},a);clearTimeout(N);N=void 0;ea();w=r=!1;H();S.deactivateTrap(k,y);var d=t(b,"onDeactivate"),g=t(b,"onPostDeactivate");a=t(b,"checkCanReturnFocus");var l=t(b,"returnFocus","returnFocusOnDeactivate");null===d||void 0===d||d();b=function(){setTimeout(function(){l&&x(X(M));null===g||void 0===g||g()},0)};if(l&&a)return a(X(M)).then(b,b),this;b();return this},pause:function(a){if(w||!r)return this;var b=t(a,"onPause");a=t(a,"onPostPause");w=!0;null===b||void 0===
b||b();ea();H();null===a||void 0===a||a();return this},unpause:function(a){if(!w||!r)return this;var b=t(a,"onUnpause");a=t(a,"onPostUnpause");w=!1;null===b||void 0===b||b();G();da();H();null===a||void 0===a||a();return this},updateContainerElements:function(a){z=[].concat(a).filter(Boolean).map(function(b){return"string"===typeof b?e.querySelector(b):b});r&&G();H();return this}};y.updateContainerElements(c);return y};I.activateFocusTrap=function(c,f){c.focusTrapDisabled||c.focusTrap?.activate(f)};
I.connectFocusTrap=function(c,f){const {el:e}=c,k=f?.focusTrapEl||e;k&&(c.focusTrap=ma(k,{clickOutsideDeactivates:!0,escapeDeactivates:!1,fallbackFocus:k,setReturnFocus:h=>{m.focusElement(h);return!1},...f?.focusTrapOptions,document:e.ownerDocument,tabbableOptions:m.tabbableOptions,trapStack:fa.focusTrapStack}))};I.deactivateFocusTrap=function(c,f){c.focusTrap?.deactivate(f)};I.updateFocusTrapElements=function(c){c.focusTrap?.updateContainerElements(c.el)}});