// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.31/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/tslib.es6 ../../../../Graphic ../../../../core/Accessor ../../../../core/handleUtils ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/reactiveUtils ../../../../core/accessorSupport/decorators/property ../../../../core/has ../../../../core/Logger ../../../../core/RandomLCG ../../../../core/accessorSupport/decorators/subclass ../../../../core/accessorSupport/diffUtils ../../../../core/support/UpdatingHandles ../../../../layers/Layer ../../../../layers/graphics/hydratedFeatures ../../../../renderers/support/renderingInfoUtils ../../../../rest/support/Query ../interfaces ./constants ./Graphics3DCore ./Graphics3DElevationAlignment ./Graphics3DFrustumVisibility ./Graphics3DObjectStates ./Graphics3DScaleVisibility ./graphicUtils ../support/highlightUtils ../../webgl-engine/lib/UpdatePolicy".split(" "),
function(c,d,q,r,m,n,t,k,f,L,M,N,u,v,w,x,y,p,z,A,B,C,D,E,F,G,H,I,J){c.GraphicsProcessor=class extends r{constructor(a){super(a);this.type="graphics-3d";this.graphicsCore=null;this.drapeSourceType=A.DrapeSourceType.Features;this.frustumVisibilityEnabled=this.scaleVisibilityEnabled=!1;this._suspendResumeExtent=null;this._updatingHandles=new w.UpdatingHandles}initialize(){const {layer:a}=this,b="effectiveScaleRange"in a?a:null,g=new C.Graphics3DCore({owner:this,layer:this.owner.layer,preferredUpdatePolicy:J.UpdatePolicy.SYNC,
graphicSymbolSupported:!0,componentFactories:{elevationAlignment:(e,h)=>new D.Graphics3DElevationAlignment({graphicsCoreOwner:this,graphicsCore:e,queryGraphicUIDsInExtent:h,elevationProvider:this.view.elevationProvider}),scaleVisibility:this.scaleVisibilityEnabled&&null!=b?(e,h)=>new G.Graphics3DScaleVisibility({graphicsCoreOwner:this,layer:b,queryGraphicUIDsInExtent:h,graphicsCore:e,basemapTerrain:this.owner.view.basemapTerrain}):null,objectStates:e=>new F.Graphics3DObjectStates(e)}});this._set("graphicsCore",
g);this.frustumVisibilityEnabled&&this._set("frustumVisibility",new E.Graphics3DFrustumVisibility({graphicsCoreOwner:this}));if("fullOpacity"in this.owner){const e=this.owner;this._updatingHandles.add(()=>e.fullOpacity,()=>this.graphicsCore.opacityChange())}"elevationInfo"in a&&this._updatingHandles.add(()=>a.elevationInfo,(e,h)=>{v.diff(e,h)&&this._updatingHandles.addPromise(this.graphicsCore.elevationInfoChange())});this._set("initializePromise",this._initializeAsync());this._updatingHandles.addPromise(this.initializePromise)}async _initializeAsync(){try{await this.graphicsCore.initializePromise}catch(a){if(t.isAbortError(a))return;
throw a;}this.destroyed||(this.addHandles(k.watch(()=>this.view.clippingArea,()=>this._updateClippingExtent(),k.sync)),this._updateClippingExtent(),this._setupSuspendResumeExtent(),this.graphicsCore.startCreateGraphics())}destroy(){this._updatingHandles.destroy();this._set("frustumVisibility",n.destroyMaybe(this.frustumVisibility));this._set("graphicsCore",n.destroyMaybe(this.graphicsCore))}get layer(){return this.owner.layer}get view(){return this.owner.view}get scaleVisibility(){return this.graphicsCore?.scaleVisibility}get elevationAlignment(){return this.graphicsCore?.elevationAlignment}get scaleVisibilitySuspended(){return!(null==
this.scaleVisibility||!this.scaleVisibility.suspended)}get frustumVisibilitySuspended(){return null!=this.frustumVisibility&&this.frustumVisibility.suspended}get suspended(){return this.owner.suspended??!1}get updating(){return!!(this.graphicsCore?.updating||null!=this.scaleVisibility&&this.scaleVisibility.updating||null!=this.frustumVisibility&&this.frustumVisibility.updating||this._updatingHandles.updating)}get graphics3DGraphics(){return this.graphicsCore?.graphics3DGraphics}get graphics3DGraphicsByObjectID(){return this.graphicsCore?.graphics3DGraphicsByObjectID}get loadedGraphics(){return this.owner.loadedGraphics}get fullOpacity(){return this.owner.fullOpacity??
1}get slicePlaneEnabled(){return this.owner.slicePlaneEnabled}get updatePolicy(){return this.owner.updatePolicy}notifyGraphicGeometryChanged(a){this.graphicsCore.notifyGraphicGeometryChanged(a)}notifyGraphicVisibilityChanged(a){this.graphicsCore.notifyGraphicVisibilityChanged(a)}getRenderingInfo(a,b,g){a=p.getRenderingInfo(a,{renderer:b,arcade:g});a?.color&&(b=a.color,b[0]/=255,b[1]/=255,b[2]/=255);return a}getRenderingInfoAsync(a,b,g,e){return p.getRenderingInfoAsync(a,{renderer:b,arcade:g,...e})}getHit(a){if(this.owner.loadedGraphics){var b=
this.owner.loadedGraphics.find(g=>g.uid===a);if(b)return b=y.hydrateGraphic(b,this.layer instanceof x?this.layer:null),{type:"graphic",graphic:b,layer:b.layer}}return null}whenGraphicBounds(a,b){return this.graphicsCore?this.graphicsCore.whenGraphicBounds(a,b):Promise.reject()}computeAttachmentOrigin(a,b){return this.graphicsCore?this.graphicsCore.computeAttachmentOrigin(a,b):null}getSymbolLayerSize(a,b){return this.graphicsCore?this.graphicsCore.getSymbolLayerSize(a,b):null}maskOccludee(a){const b=
this.graphicsCore?.objectStates;if(!b)return m.makeHandle();const {set:g,handle:e}=b.acquireOccludeeSet(null);b.setUid(g,a.uid);return e}highlight(a,b){const g=this.graphicsCore?.objectStates;if(!g||a instanceof z)return l;a=I.normalizeHighlightTargetExceptQuery(a);if(0===a.length)return l;if(a[0]instanceof q){a=a.map(K=>K.uid);const {set:e,handle:h}=g.acquireHighlightSet(b,null);g.setUids(e,a);return h}if("number"===typeof a[0]){const {set:e,handle:h}=g.acquireHighlightSet(b,null);g.setObjectIds(e,
a);return h}return l}_setupSuspendResumeExtent(){const {scaleVisibility:a,frustumVisibility:b}=this;if(null!=a||null!=b){var g=({computedExtent:e,extentPadding:h})=>{this._suspendResumeExtent=H.enlargeExtent(e,this._suspendResumeExtent,B.suspendResumeExtentOptimism,h);null!=a&&a.setExtent(this._suspendResumeExtent);null!=b&&b.setExtent(this._suspendResumeExtent)};this.addHandles(k.watch(()=>({computedExtent:this.graphicsCore?.computedExtent,extentPadding:this.graphicsCore?.extentPadding}),e=>g(e),
k.syncAndInitial))}}_updateClippingExtent(){this.graphicsCore.setClippingExtent(this.view.clippingArea,this.view.spatialReference)&&this.graphicsCore.recreateAllGraphics()}};d.__decorate([f.property()],c.GraphicsProcessor.prototype,"type",void 0);d.__decorate([f.property({constructOnly:!0})],c.GraphicsProcessor.prototype,"owner",void 0);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"layer",null);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"view",null);d.__decorate([f.property({constructOnly:!0})],
c.GraphicsProcessor.prototype,"graphicsCore",void 0);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"scaleVisibility",null);d.__decorate([f.property({constructOnly:!0})],c.GraphicsProcessor.prototype,"frustumVisibility",void 0);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"elevationAlignment",null);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"scaleVisibilitySuspended",null);d.__decorate([f.property({readOnly:!0})],c.GraphicsProcessor.prototype,"frustumVisibilitySuspended",
null);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"suspended",null);d.__decorate([f.property({readOnly:!0})],c.GraphicsProcessor.prototype,"updating",null);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"loadedGraphics",null);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"fullOpacity",null);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"slicePlaneEnabled",null);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"drapeSourceType",void 0);d.__decorate([f.property()],
c.GraphicsProcessor.prototype,"updatePolicy",null);d.__decorate([f.property({constructOnly:!0})],c.GraphicsProcessor.prototype,"scaleVisibilityEnabled",void 0);d.__decorate([f.property({constructOnly:!0})],c.GraphicsProcessor.prototype,"frustumVisibilityEnabled",void 0);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"initializePromise",void 0);c.GraphicsProcessor=d.__decorate([u.subclass("esri.views.3d.layers.graphics.GraphicsProcessor")],c.GraphicsProcessor);const l=m.makeHandle();Object.defineProperty(c,
Symbol.toStringTag,{value:"Module"})});