// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.31/esri/copyright.txt for details.
//>>built
define("exports ./componentsUtils ./dom ./loadable ./locale ./t9n ./interactive ./icon".split(" "),function(q,b,g,f,h,e,k,r){function l(){"undefined"!==typeof customElements&&["calcite-handle","calcite-icon"].forEach(a=>{switch(a){case "calcite-handle":customElements.get(a)||customElements.define(a,t);break;case "calcite-icon":customElements.get(a)||r.defineCustomElement()}})}const t=b.proxyCustomElement(class extends b.H{constructor(){super();this.__registerHost();this.__attachShadow();this.calciteHandleChange=
b.createEvent(this,"calciteHandleChange",6);this.calciteHandleNudge=b.createEvent(this,"calciteHandleNudge",6);this.calciteInternalAssistiveTextChange=b.createEvent(this,"calciteInternalAssistiveTextChange",6);this.handleKeyDown=a=>{if(!this.disabled)switch(a.key){case " ":this.selected=!this.selected;this.calciteHandleChange.emit();a.preventDefault();break;case "ArrowUp":if(!this.selected)break;a.preventDefault();this.calciteHandleNudge.emit({direction:"up"});break;case "ArrowDown":this.selected&&
(a.preventDefault(),this.calciteHandleNudge.emit({direction:"down"}))}};this.handleBlur=()=>{this.blurUnselectDisabled||this.disabled||!this.selected||(this.selected=!1,this.calciteHandleChange.emit())};this.disabled=this.selected=!1;this.label=this.setSize=this.setPosition=this.messages=this.dragHandle=void 0;this.blurUnselectDisabled=!1;this.defaultMessages=this.effectiveLocale=this.messageOverrides=void 0}handleAriaTextChange(){const a=this.getAriaText("live");a&&this.calciteInternalAssistiveTextChange.emit({message:a})}onMessagesChange(){}connectedCallback(){e.connectMessages(this);
h.connectLocalized(this)}async componentWillLoad(){f.setUpLoadableComponent(this);await e.setUpMessages(this)}componentDidLoad(){f.setComponentLoaded(this)}componentDidRender(){k.updateHostInteraction(this)}disconnectedCallback(){e.disconnectMessages(this);h.disconnectLocalized(this)}effectiveLocaleChange(){e.updateMessages(this,this.effectiveLocale)}async setFocus(){await f.componentFocusable(this);this.handleButton?.focus()}getTooltip(){const {label:a,messages:c}=this;return c?a?c.dragHandle.replace("{itemLabel}",
a):c.dragHandleUntitled:""}getAriaText(a){const {setPosition:c,setSize:m,label:n,messages:d,selected:p}=this;return d&&n&&"number"===typeof m&&"number"===typeof c?("label"===a?p?d.dragHandleChange:d.dragHandleIdle:p?d.dragHandleActive:d.dragHandleCommit).replace("{position}",c.toString()).replace("{itemLabel}",n).replace("{total}",m.toString()):null}render(){return b.h(k.InteractiveContainer,{key:"1a694de393421691c83e7265850275c217ef7ffe",disabled:this.disabled},b.h("span",{key:"82ff692c15c2d9294ceb814b3f7f06bb4d8ff0e0",
"aria-checked":this.disabled?null:g.toAriaBoolean(this.selected),"aria-disabled":this.disabled?g.toAriaBoolean(this.disabled):null,"aria-label":this.disabled?null:this.getAriaText("label"),class:{handle:!0,["handle--selected"]:!this.disabled&&this.selected},onBlur:this.handleBlur,onKeyDown:this.handleKeyDown,ref:a=>{this.handleButton=a},role:"radio",tabIndex:this.disabled?null:0,title:this.getTooltip()},b.h("calcite-icon",{key:"25862a953826aea2d594507157aaffc21d07001c",icon:"drag",scale:"s"})))}static get assetsDirs(){return["assets"]}get el(){return this}static get watchers(){return{messages:["handleAriaTextChange"],
label:["handleAriaTextChange"],selected:["handleAriaTextChange"],setPosition:["handleAriaTextChange"],setSize:["handleAriaTextChange"],messageOverrides:["onMessagesChange"],effectiveLocale:["effectiveLocaleChange"]}}static get style(){return":host([disabled]){cursor:default;-webkit-user-select:none;user-select:none;opacity:var(--calcite-opacity-disabled)}:host([disabled]) *,:host([disabled]) ::slotted(*){pointer-events:none}:host{display:flex}.handle{display:flex;align-items:center;justify-content:center;align-self:stretch;border-style:none;outline-color:transparent;color:var(--calcite-handle-icon-color, var(--calcite-color-border-input));background-color:var(--calcite-handle-background-color, transparent);padding-block:0.75rem;padding-inline:0.25rem;line-height:0}.handle calcite-icon{color:inherit}:host(:not([disabled])) .handle{cursor:move}:host(:not([disabled])) .handle:hover{color:var(--calcite-handle-icon-color-hover, var(--calcite-color-text-1));background-color:var(--calcite-handle-background-color-hover, var(--calcite-color-foreground-2))}:host(:not([disabled])) .handle:focus{outline:2px solid var(--calcite-ui-focus-color, var(--calcite-color-brand));outline-offset:calc(\n            -2px *\n            calc(\n              1 -\n              2 * clamp(\n                0,\n                var(--calcite-offset-invert-focus),\n                1\n              )\n            )\n          );color:var(--calcite-handle-icon-color-hover, var(--calcite-color-text-1))}:host(:not([disabled])) .handle--selected{color:var(--calcite-handle-icon-color-selected, var(--calcite-color-text-1));background-color:var(--calcite-handle-background-color-selected, var(--calcite-color-foreground-3))}:host([disabled]) ::slotted([calcite-hydrated][disabled]),:host([disabled]) [calcite-hydrated][disabled]{opacity:1}.interaction-container{display:contents}:host([hidden]){display:none}[hidden]{display:none}"}},
[1,"calcite-handle",{selected:[1540],disabled:[516],dragHandle:[513,"drag-handle"],messages:[1040],setPosition:[2,"set-position"],setSize:[2,"set-size"],label:[1],blurUnselectDisabled:[4,"blur-unselect-disabled"],messageOverrides:[1040],effectiveLocale:[32],defaultMessages:[32],setFocus:[64]},void 0,{messages:["handleAriaTextChange"],label:["handleAriaTextChange"],selected:["handleAriaTextChange"],setPosition:["handleAriaTextChange"],setSize:["handleAriaTextChange"],messageOverrides:["onMessagesChange"],
effectiveLocale:["effectiveLocaleChange"]}]);l();q.defineCustomElement=l});