// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.31/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/tslib.es6 ../../core/Accessor ../../core/has ../../core/Logger ../../core/promiseUtils ../../core/accessorSupport/decorators/property ../../core/RandomLCG ../../core/accessorSupport/decorators/subclass ./interfaces ./ManipulatorCollection".split(" "),function(b,c,h,n,p,k,d,q,l,e,m){b.InteractiveToolBase=class extends h{constructor(a){super(a);this.manipulators=new m.ManipulatorCollection;this.automaticManipulatorSelection=!0;this.hasHoveredManipulators=this.hasGrabbedManipulators=
!1;this.firstGrabbedManipulator=null;this.created=!1;this.removeIncompleteOnCancel=!0;this._editableFlags=new Map([[e.EditableFlag.MANAGER,!0],[e.EditableFlag.USER,!0]]);this._creationFinishedResolver=k.createResolver()}get active(){return null!=this.view&&this.view.activeTool===this}set visible(a){this._get("visible")!==a&&(this._set("visible",a),this._syncVisible())}get editable(){return this.getEditableFlag(e.EditableFlag.USER)}set editable(a){this.setEditableFlag(e.EditableFlag.USER,a)}get updating(){return!1}get cursor(){return null}get hasFocusedManipulators(){return this.hasGrabbedManipulators||
this.hasHoveredManipulators}destroy(){this.manipulators.destroy();this._set("view",null)}onAdd(){this._syncVisible()}activate(){null!=this.view&&(this.view.focus(),this.onActivate())}deactivate(){this.onDeactivate()}handleInputEvent(a){this.onInputEvent(a)}handleInputEventAfter(a){this.onInputEventAfter(a)}setEditableFlag(a,f){this._editableFlags.set(a,f);this.manipulators.isToolEditable=this.internallyEditable;this._updateManipulatorAttachment();a===e.EditableFlag.USER&&this.notifyChange("editable");
this.onEditableChange();this.onManipulatorSelectionChanged()}getEditableFlag(a){return this._editableFlags.get(a)??!1}endDrag(){const a=this.view.inputManager.latestPointerLocation;if(a){var f=!1;this.manipulators.forEach(({manipulator:g})=>{g.dragging&&(f=!0,g.events.emit("drag",{action:"end",start:a,screenPoint:a}))});f&&(this.view.toolViewManager.activeTool=null)}}whenCreated(){return this._creationFinishedResolver.promise}onManipulatorSelectionChanged(){}onActivate(){}onDeactivate(){}onShow(){}onHide(){}onEditableChange(){}onInputEvent(a){}onInputEventAfter(a){}get internallyEditable(){return this.getEditableFlag(e.EditableFlag.USER)&&
this.getEditableFlag(e.EditableFlag.MANAGER)}finishToolCreation(){this.created||this._creationFinishedResolver.resolve(this);this._set("created",!0)}_syncVisible(){this.initialized&&(this.visible?this._show():(this._hide(),this.active&&(this.view.activeTool=null)))}_show(){this._updateManipulatorAttachment();this.onShow()}_hide(){this._updateManipulatorAttachment();this.onHide()}_updateManipulatorAttachment(){this.visible?this.manipulators.attach():this.manipulators.detach()}};c.__decorate([d.property({constructOnly:!0})],
b.InteractiveToolBase.prototype,"view",void 0);c.__decorate([d.property({readOnly:!0})],b.InteractiveToolBase.prototype,"active",null);c.__decorate([d.property({value:!0})],b.InteractiveToolBase.prototype,"visible",null);c.__decorate([d.property({value:!0})],b.InteractiveToolBase.prototype,"editable",null);c.__decorate([d.property({readOnly:!0})],b.InteractiveToolBase.prototype,"manipulators",void 0);c.__decorate([d.property({readOnly:!0})],b.InteractiveToolBase.prototype,"updating",null);c.__decorate([d.property()],
b.InteractiveToolBase.prototype,"cursor",null);c.__decorate([d.property({readOnly:!0})],b.InteractiveToolBase.prototype,"automaticManipulatorSelection",void 0);c.__decorate([d.property()],b.InteractiveToolBase.prototype,"hasFocusedManipulators",null);c.__decorate([d.property()],b.InteractiveToolBase.prototype,"hasGrabbedManipulators",void 0);c.__decorate([d.property()],b.InteractiveToolBase.prototype,"hasHoveredManipulators",void 0);c.__decorate([d.property()],b.InteractiveToolBase.prototype,"firstGrabbedManipulator",
void 0);c.__decorate([d.property({readOnly:!0})],b.InteractiveToolBase.prototype,"created",void 0);c.__decorate([d.property({readOnly:!0})],b.InteractiveToolBase.prototype,"removeIncompleteOnCancel",void 0);b.InteractiveToolBase=c.__decorate([l.subclass("esri.views.interactive.InteractiveToolBase")],b.InteractiveToolBase);Object.defineProperty(b,Symbol.toStringTag,{value:"Module"})});