// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.31/esri/copyright.txt for details.
//>>built
define("require ../../chunks/tslib.es6 ../../request ../../core/has ../../core/jsonMap ../../core/JSONSupport ../../core/promiseUtils ../../core/accessorSupport/decorators/property ../../core/Logger ../../core/RandomLCG ../../core/accessorSupport/decorators/enumeration ../../core/accessorSupport/decorators/subclass ../utils ../geoprocessor/GPOptions ../geoprocessor/utils ./GPMessage".split(" "),function(x,k,p,w,y,e,l,m,E,F,z,A,n,B,q,C){var r;w=y.strict()({esriJobCancelled:"job-cancelled",esriJobCancelling:"job-cancelling",
esriJobDeleted:"job-deleted",esriJobDeleting:"job-deleting",esriJobTimedOut:"job-timed-out",esriJobExecuting:"job-executing",esriJobFailed:"job-failed",esriJobNew:"job-new",esriJobSubmitted:"job-submitted",esriJobSucceeded:"job-succeeded",esriJobWaiting:"job-waiting"},{ignoreUnknown:!1});e=r=class extends e.JSONSupport{constructor(a){super(a);this.sourceUrl=this.requestOptions=this.progress=this.messages=this.jobStatus=this.jobId=null;this._jobCompletionTimer=this._cancelJobTimer=void 0}async cancelJob(a){const {jobId:b,
sourceUrl:d}=this;var {path:c}=n.parseUrl(d);const f={...this.requestOptions,...a,query:{f:"json"}};({data:c}=await p(`${c}/jobs/${b}/cancel`,f));const {messages:g,jobStatus:h,progress:t}=r.fromJSON(c);this.set({messages:g,jobStatus:h,progress:t});return"job-cancelled"===h?this:new Promise((u,v)=>{l.onAbort(f.signal,()=>{this._clearCancelJobTimer();v(l.createAbortError())});this._clearCancelJobTimer();this._cancelJobTimer=setInterval(()=>{this._cancelJobTimer||v(l.createAbortError());this.checkJobStatus(a).then(({jobStatus:D})=>
{switch(D){case "job-deleted":case "job-deleting":case "job-executing":case "job-failed":case "job-new":case "job-submitted":case "job-succeeded":case "job-timed-out":case "job-waiting":this._clearCancelJobTimer();v(this);break;case "job-cancelled":this._clearCancelJobTimer(),u(this)}})},1E3)})}destroy(){clearInterval(this._cancelJobTimer);clearInterval(this._jobCompletionTimer)}async checkJobStatus(a){const {path:b}=n.parseUrl(this.sourceUrl);({data:a}=await p(`${b}/jobs/${this.jobId}`,{...this.requestOptions,
...a,query:{f:"json"}}));const {messages:d,jobStatus:c,progress:f}=r.fromJSON(a);this.set({messages:d,jobStatus:c,progress:f});return this}async fetchResultData(a,b,d){b=B.from(b||{});const {returnColumnName:c,returnFeatureCollection:f,returnM:g,returnZ:h,outSpatialReference:t}=b;({path:b}=n.parseUrl(this.sourceUrl));const u=q.gpEncode({returnColumnName:c||null,returnFeatureCollection:f||null,returnM:g||null,returnZ:h||null,outSR:t,returnType:"data",f:"json"},null);({data:a}=await p(`${b}/jobs/${this.jobId}/results/${a}`,
{...this.requestOptions,...d,query:u}));return q.decode(a)}async fetchResultImage(a,b,d){const {path:c}=n.parseUrl(this.sourceUrl);b={...b.toJSON(),f:"json"};b=q.gpEncode(b);({data:a}=await p(`${c}/jobs/${this.jobId}/results/${a}`,{...this.requestOptions,...d,query:b}));return q.decode(a)}async fetchResultMapImageLayer(){var {path:a}=n.parseUrl(this.sourceUrl);const b=a.indexOf("/GPServer/");a=`${a.slice(0,Math.max(0,b))}/MapServer/jobs/${this.jobId}`;return new (await new Promise((d,c)=>x(["../../layers/MapImageLayer"],
f=>d(Object.freeze(Object.defineProperty({__proto__:null,default:f},Symbol.toStringTag,{value:"Module"}))),c))).default({url:a})}async waitForJobCompletion(a={}){const {interval:b=1E3,signal:d,statusCallback:c}=a;return new Promise((f,g)=>{l.onAbort(d,()=>{this._clearJobCompletionTimer();g(l.createAbortError())});this._clearJobCompletionTimer();this._jobCompletionTimer=setInterval(()=>{this._jobCompletionTimer||g(l.createAbortError());this.checkJobStatus().then(({jobStatus:h})=>{switch(h){case "job-succeeded":this._clearJobCompletionTimer();
f(this);break;case "job-executing":case "job-new":case "job-submitted":case "job-waiting":c&&c(this);break;case "job-cancelled":case "job-cancelling":case "job-deleted":case "job-deleting":case "job-failed":case "job-timed-out":this._clearJobCompletionTimer(),g(this)}}).catch(h=>{this._clearJobCompletionTimer();g(h)})},b)})}_clearCancelJobTimer(){clearInterval(this._cancelJobTimer);this._cancelJobTimer=void 0}_clearJobCompletionTimer(){clearInterval(this._jobCompletionTimer);this._jobCompletionTimer=
void 0}};k.__decorate([m.property()],e.prototype,"jobId",void 0);k.__decorate([z.enumeration(w,{ignoreUnknown:!1})],e.prototype,"jobStatus",void 0);k.__decorate([m.property({type:[C]})],e.prototype,"messages",void 0);k.__decorate([m.property()],e.prototype,"progress",void 0);k.__decorate([m.property()],e.prototype,"requestOptions",void 0);k.__decorate([m.property({json:{write:!0}})],e.prototype,"sourceUrl",void 0);return e=r=k.__decorate([A.subclass("esri.rest.support.JobInfo")],e)});