// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.31/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/tslib.es6 ../../../core/Collection ../../../core/collectionUtils ../../../core/Error ../../../core/Logger ../../../core/reactiveUtils ../../../core/accessorSupport/decorators/property ../../../core/has ../../../core/RandomLCG ../../../core/accessorSupport/decorators/subclass ../../../linkChart/utils ../engine/Container ./support/util ../support/HighlightGroup ../support/highlightGroupUtils ../support/HighlightOptions ../../layers/support/ClipRect ../../layers/support/Geometry ../../layers/support/Path ../../support/layerViewUtils".split(" "),
function(n,e,h,r,t,u,d,f,F,G,v,w,x,y,p,q,z,A,B,C,D){const k=h.ofType({key:"type",base:null,typeMap:{rect:A,path:C,geometry:B}}),E=new (h.ofType(p.HighlightGroup));n.LayerView2DMixin=c=>{c=class extends c{constructor(){super(...arguments);this.attached=!1;this.clips=new k;this.highlights=null;this.lastUpdateId=-1;this.updateRequested=this.moving=!1;this._visibleAtCurrentScale=!0}initialize(){const b=this.view?.spatialReferenceLocked??!0;this.view?.spatialReference&&b&&!this.spatialReferenceSupported?
this.addResolvingPromise(Promise.reject(new t("layerview:spatial-reference-incompatible","The spatial reference of this layer does not meet the requirements of the view",{layer:this.layer}))):(this.container||(this.container=new x.Container),this.container.fadeTransitionEnabled=!0,this.container.visible=!1,this.container.endTransitions(),this.addHandles([d.watch(()=>this.suspended,a=>{this.container&&(this.container.visible=!a)},d.syncAndInitial),d.watch(()=>this.updateSuspended,a=>{this.view&&!a&&
this.updateRequested&&this.view.requestUpdate()},d.syncAndInitial),d.watch(()=>this.layer?.opacity??1,a=>{this.container&&(this.container.opacity=a)},d.syncAndInitial),d.watch(()=>this.layer&&"blendMode"in this.layer?this.layer.blendMode:"normal",a=>{this.container&&(this.container.blendMode=a)},d.syncAndInitial),d.watch(()=>this.layer&&"effect"in this.layer?this.layer.effect:null,a=>{this.container&&(this.container.effect=a)},d.syncAndInitial),d.watch(()=>this._mergedHighlights.items.map(a=>({name:a.name,
options:{fillColor:a.options.color,haloColor:a.options.haloColor,fillOpacity:a.options.fillOpacity,haloOpacity:a.options.haloOpacity,haloWidth:a.options.haloWidth,haloBlur:a.options.haloBlur}})),()=>{this.container.highlightGradient=y.createOrReuseHighlightGradient(this.container.highlightGradient,this._mergedHighlights.items)},d.syncAndInitial),d.watch(()=>this._mergedHighlights.items.map(a=>a.name),()=>{this._updateHighlights()}),d.on(()=>this.clips,"change",()=>{this.container&&(this.container.clips=
this.clips)},d.syncAndInitial),d.watch(()=>({scale:this.view?.scale,scaleRange:this.layer&&"effectiveScaleRange"in this.layer?this.layer.effectiveScaleRange:null}),({scale:a,scaleRange:g})=>{a=D.isInEffectiveScaleRange(g,a);a!==this._visibleAtCurrentScale&&(this._visibleAtCurrentScale=a)},d.syncAndInitial)],"constructor"),this.view?.whenLayerView?this.view.whenLayerView(this.layer).then(a=>{a===this&&this.processAttach()},()=>{}):this.when().then(()=>{this.processAttach()},()=>{}))}_updateHighlights(){}destroy(){this.processDetach();
this.updateRequested=!1}get highlightOptions(){return q.getDefaultHighlightOptions(this)}set highlightOptions(b){q.setDefaultHighlightOptions(this,b)}get _mergedHighlights(){if(!this.view)return E;if(!this.highlights)return this.view.highlights;const b=this.view.highlights.clone();for(const a of this.highlights){const g=b.find(l=>l.name===a.name);g&&(g.options=a.options)}return b}get scheduler(){return this.view.scheduler}get spatialReferenceSupported(){const b=this.view?.spatialReference;return null==
b||this.supportsSpatialReference(b)}get updating(){return this.spatialReferenceSupported&&(!this.attached||!this.suspended&&(this.updateRequested||this.isUpdating())||!!this._updatingHandles?.updating||this.container.transitioning)}get visibleAtCurrentScale(){return this._visibleAtCurrentScale}processAttach(){this.isResolved()&&!this.attached&&!this.destroyed&&this.spatialReferenceSupported&&(this.attach(),this.attached=!0,this.requestUpdate())}processDetach(){this.attached&&(this.attached=!1,this.removeHandles("attach"),
this.detach(),this.updateRequested=!1)}requestUpdate(){this.destroyed||this.updateRequested||(this.updateRequested=!0,this.updateSuspended||this.view.requestUpdate())}processUpdate(b){this.isFulfilled()&&!this.isResolved()?this.updateRequested=!1:(this._set("updateParameters",b),this.updateRequested&&!this.updateSuspended&&(this.updateRequested=!1,this.update(b)))}hitTest(b,a){return Promise.resolve(null)}supportsSpatialReference(b){return!0}canResume(){if(!this.spatialReferenceSupported)return!1;
switch(this.layer?.type){case "link-chart":case "knowledge-graph-sublayer":break;default:if(w.isLinkChartView(this.view)&&!this.view.inGeographicLayout)return!1}return super.canResume()?this.visibleAtCurrentScale:!1}getSuspendInfo(){const b=super.getSuspendInfo(),a=!this.spatialReferenceSupported;a&&(b.spatialReferenceNotSupported=a);return b}addAttachHandles(b){this.addHandles(b,"attach")}_getHighlightBits(b){b=new Set(b);let a=1,g=0;if(!this.view)return 0;const l=this._mergedHighlights;for(const {name:m}of l)b.delete(m)&&
(g=a),a<<=1;for(const m of b)u.getLogger(this).error("#highlights",`${m} was not found. Features in this group will not be highlighted.`);return g}};e.__decorate([f.property()],c.prototype,"attached",void 0);e.__decorate([f.property({type:k,set(b){b=r.referenceSetter(b,this._get("clips"),k);this._set("clips",b)}})],c.prototype,"clips",void 0);e.__decorate([f.property()],c.prototype,"container",void 0);e.__decorate([f.property({type:z})],c.prototype,"highlightOptions",null);e.__decorate([f.property({type:h.ofType(p.HighlightGroup)})],
c.prototype,"highlights",void 0);e.__decorate([f.property()],c.prototype,"_mergedHighlights",null);e.__decorate([f.property()],c.prototype,"moving",void 0);e.__decorate([f.property({readOnly:!0})],c.prototype,"spatialReferenceSupported",null);e.__decorate([f.property({readOnly:!0})],c.prototype,"updateParameters",void 0);e.__decorate([f.property()],c.prototype,"updateRequested",void 0);e.__decorate([f.property()],c.prototype,"updating",null);e.__decorate([f.property()],c.prototype,"view",void 0);
e.__decorate([f.property()],c.prototype,"_visibleAtCurrentScale",void 0);e.__decorate([f.property({readOnly:!0})],c.prototype,"visibleAtCurrentScale",null);return c=e.__decorate([v.subclass("esri.views.2d.layers.LayerView2D")],c)};Object.defineProperty(n,Symbol.toStringTag,{value:"Module"})});