// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.31/esri/copyright.txt for details.
//>>built
define(["exports","./_commonjsHelpers"],function(ta,R){var S={exports:{}},Z,sa=function(){if(Z)return S.exports;Z=1;(function(B,C){C=(()=>{var w="undefined"!==typeof document&&document.currentScript?document.currentScript.src:void 0;return function(q={}){function r(a){return b.locateFile?b.locateFile(a,n):n+a}function x(){var a=J.buffer;b.HEAP8=new Int8Array(a);b.HEAP16=new Int16Array(a);b.HEAPU8=K=new Uint8Array(a);b.HEAPU16=new Uint16Array(a);b.HEAP32=new Int32Array(a);b.HEAPU32=L=new Uint32Array(a);
b.HEAPF32=new Float32Array(a);b.HEAPF64=new Float64Array(a)}function aa(a){b.onAbort?.(a);a="Aborted("+a+")";y(a);ba=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");M(a);throw a;}function ca(a){if(a==D&&E)return new Uint8Array(E);if(T)return T(a);throw"both async and sync fetching of the wasm failed";}function ua(a){return E||!da&&!N||"function"!=typeof fetch?Promise.resolve().then(()=>ca(a)):fetch(a,{credentials:"same-origin"}).then(c=>{if(!c.ok)throw"failed to load wasm binary file at '"+
a+"'";return c.arrayBuffer()}).catch(()=>ca(a))}function ea(a,c,e){return ua(a).then(d=>WebAssembly.instantiate(d,c)).then(d=>d).then(e,d=>{y(`failed to asynchronously prepare wasm: ${d}`);aa(d)})}function va(a,c,e,d){return a||"function"!=typeof WebAssembly.instantiateStreaming||c.startsWith("data:application/octet-stream;base64,")||"function"!=typeof fetch?ea(c,e,d):fetch(c,{credentials:"same-origin"}).then(f=>WebAssembly.instantiateStreaming(f,e).then(d,function(g){y(`wasm streaming compile failed: ${g}`);
y("falling back to ArrayBuffer instantiation");return ea(c,e,d)}))}function fa(){function a(){if(!O&&(O=!0,b.calledRun=!0,!ba)){U(ha);ia(b);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;)ja.unshift(b.postRun.shift());U(ja)}}if(!(0<t)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)ka.unshift(b.preRun.shift());U(ka);0<t||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},
1);a()},1)):a())}}var b=q,ia,M;b.ready=new Promise((a,c)=>{ia=a;M=c});var la=Object.assign({},b),da="object"==typeof window,N="function"==typeof importScripts;"object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node;var n="",T;if(da||N)N?n=self.location.href:"undefined"!=typeof document&&document.currentScript&&(n=document.currentScript.src),w&&(n=w),n=0!==n.indexOf("blob:")?n.substr(0,n.replace(/[?#].*/,"").lastIndexOf("/")+1):"",N&&(T=a=>{var c=new XMLHttpRequest;
c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});var wa=b.print||console.log.bind(console),y=b.printErr||console.error.bind(console);Object.assign(b,la);la=null;b.arguments&&b.arguments;b.thisProgram&&b.thisProgram;b.quit&&b.quit;var E;b.wasmBinary&&(E=b.wasmBinary);"object"!=typeof WebAssembly&&aa("no native wasm support detected");var J,ba=!1,K,L,ka=[],ha=[],ja=[],t=0,F=null;var D="libtess.wasm";D.startsWith("data:application/octet-stream;base64,")||
(D=r(D));var U=a=>{for(;0<a.length;)a.shift()(b)};b.noExitRuntime||!0;var xa=[null,[],[]],ma="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,P=[],na,Q=a=>{var c=P[a];c||(a>=P.length&&(P.length=a+1),P[a]=c=na.get(a));return c},ya={e:()=>{throw Infinity;},g:(a,c,e)=>K.copyWithin(a,c,c+e),f:a=>{var c=K.length;a>>>=0;if(2147483648<a)return!1;for(var e=1;4>=e;e*=2){var d=c*(1+.2/e);d=Math.min(d,a+100663296);var f=Math;d=Math.max(a,d);a:{f=(f.min.call(f,2147483648,d+(65536-d%65536)%65536)-
J.buffer.byteLength+65535)/65536;try{J.grow(f);x();var g=1;break a}catch(l){}g=void 0}if(g)return!0}return!1},c:(a,c,e,d)=>{for(var f=0,g=0;g<e;g++){var l=L[c>>2],oa=L[c+4>>2];c+=8;for(var V=0;V<oa;V++){var h=K[l+V],W=xa[a];if(0===h||10===h){h=W;for(var p=0,u=p+void 0,z=p;h[z]&&!(z>=u);)++z;if(16<z-p&&h.buffer&&ma)h=ma.decode(h.subarray(p,z));else{for(u="";p<z;){var k=h[p++];if(k&128){var X=h[p++]&63;if(192==(k&224))u+=String.fromCharCode((k&31)<<6|X);else{var pa=h[p++]&63;k=224==(k&240)?(k&15)<<
12|X<<6|pa:(k&7)<<18|X<<12|pa<<6|h[p++]&63;65536>k?u+=String.fromCharCode(k):(k-=65536,u+=String.fromCharCode(55296|k>>10,56320|k&1023))}}else u+=String.fromCharCode(k)}h=u}(1===a?wa:y)(h);W.length=0}else W.push(h)}f+=oa}L[d>>2]=f;return 0},b:function(a,c){var e=G();try{return Q(a)(c)}catch(d){H(e);if(d!==d+0)throw d;I(1,0)}},h:function(a,c,e,d){var f=G();try{return Q(a)(c,e,d)}catch(g){H(f);if(g!==g+0)throw g;I(1,0)}},d:function(a,c){var e=G();try{Q(a)(c)}catch(d){H(e);if(d!==d+0)throw d;I(1,0)}},
a:function(a,c,e){var d=G();try{Q(a)(c,e)}catch(f){H(d);if(f!==f+0)throw f;I(1,0)}}},m=function(){function a(e,d){m=e.exports;J=m.i;x();na=m.m;ha.unshift(m.j);t--;b.monitorRunDependencies?.(t);0==t&&F&&(e=F,F=null,e());return m}var c={a:ya};t++;b.monitorRunDependencies?.(t);if(b.instantiateWasm)try{return b.instantiateWasm(c,a)}catch(e){y(`Module.instantiateWasm callback failed with error: ${e}`),M(e)}va(E,D,c,function(e){a(e.instance)}).catch(M);return{}}();b._malloc=a=>(b._malloc=m.k)(a);b._free=
a=>(b._free=m.l)(a);b._triangulate=(a,c,e,d,f,g)=>(b._triangulate=m.n)(a,c,e,d,f,g);var I=(a,c)=>(I=m.o)(a,c),G=()=>(G=m.p)(),H=a=>(H=m.q)(a),O;F=function c(){O||fa();O||(F=c)};if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();fa();let qa=null,v=null,A=null,Y=null,ra=0;b.triangulate=(c,e,d)=>{qa||=b._triangulate;var f=b.HEAPF32;const g=b.HEAP32.BYTES_PER_ELEMENT;var l=f.BYTES_PER_ELEMENT;d>ra&&(ra=d,A&&(b._free(A),A=0),v&&(b._free(v),v=0));
A||=b._malloc(d*l);Y||=b._malloc(4E3*g);d*=2;v||=b._malloc(d*l);f=b.HEAPF32;f.set(c,A/l);b.HEAP32.set(e,Y/g);c=qa(A,Y,Math.min(e.length,4E3),2,v,d/2);f=b.HEAPF32;f=f.slice(v/l,v/l+2*c);l={};l.buffer=f;l.vertexCount=c;return l};return q.ready}})();B.exports=C})(S);return S.exports}();R=function(B,C){for(var w=0;w<C.length;w++){const q=C[w];if("string"!==typeof q&&!Array.isArray(q))for(const r in q)if("default"!==r&&!(r in B)){const x=Object.getOwnPropertyDescriptor(q,r);x&&Object.defineProperty(B,
r,x.get?x:{enumerable:!0,get:()=>q[r]})}}return Object.freeze(Object.defineProperty(B,Symbol.toStringTag,{value:"Module"}))}({__proto__:null,default:R.getDefaultExportFromCjs(sa)},[sa]);ta.libtess=R});