// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.31/esri/copyright.txt for details.
//>>built
define("require exports ../../../chunks/tslib.es6 ../../../chunks/languageUtils ../../../core/Accessor ../../../core/arrayUtils ../../../core/Collection ../../../core/Error ../../../core/handleUtils ../../../core/has ../../../core/MapUtils ../../../core/promiseUtils ../../../core/reactiveUtils ../../../core/sql ../../../core/unitUtils ../../../core/accessorSupport/decorators/property ../../../core/Logger ../../../core/accessorSupport/decorators/subclass ../../../geometry/Extent ../../../geometry/support/scaleUtils ../../../layers/support/fieldUtils ../../../layers/support/floorFilterUtils ../../../renderers/support/clickToleranceUtils ../../../rest/identify ../../../rest/support/IdentifyParameters ../../../support/arcadeOnDemand ../../../symbols/SimpleMarkerSymbol ../../3d/layers/support/highlightUtils ./popupUtils".split(" "),
function(D,n,p,E,F,w,G,x,H,I,J,u,K,L,M,q,Y,N,O,P,Q,R,y,S,T,U,z,A,B){function C(a,b,e){const g=[];if(!a)return g;const f=d=>{var c=0===d.minScale||b<=d.minScale;const h=0===d.maxScale||b>=d.maxScale;d.visible&&c&&h&&(d.sublayers?d.sublayers.forEach(f):d.popupEnabled&&(c=B.getFetchPopupTemplate(d,{...e,defaultPopupTemplateEnabled:!1}),null!=c&&g.unshift({sublayer:d,popupTemplate:c})))};a.map(f);return g}function V(a){return a.expressionInfos?.length||Array.isArray(a.content)&&a.content.some(b=>"expression"===
b.type)?U.loadArcade():Promise.resolve()}async function W(a,b){if(a.capabilities?.operations?.supportsQuery)return!0;try{return await Promise.any(b.map(({sublayer:e})=>e.load().then(()=>e.capabilities.operations.supportsQuery)))}catch{return!1}}async function X(a,b,e){const g=a.renderer;g&&"defaultSymbol"in g&&!g.defaultSymbol&&(b=g.valueExpression?await Promise.all(b.map(f=>g.getSymbolAsync(f,e).then(d=>d?f:null))).then(f=>f.filter(d=>null!=d)):b.filter(f=>null!=g.getSymbol(f)));return b}let v=null;
n.MapServiceLayerViewHelper=class extends F{constructor(a){super(a);this._featuresResolutions=new WeakMap;this.highlightGraphicUpdated=this.highlightGraphics=null;this.updateHighlightedFeatures=u.debounce(async b=>{this.destroyed||this.updatingHandles.addPromise(this._updateHighlightedFeaturesGeometries(b).catch(()=>{}))})}initialize(){const a=b=>{this.updatingHandles.addPromise(this._updateHighlightedFeaturesSymbols(b).catch(()=>{}));this.updateHighlightedFeatures(this._highlightGeometriesResolution)};
this.addHandles([K.on(()=>this.highlightGraphics,"change",b=>a(b.added),{onListenerAdd:b=>a(b)})])}async fetchPopupFeaturesAtLocation(a,b){const {layerView:{layer:e,view:{scale:g}}}=this;if(!a)throw new x("fetchPopupFeatures:invalid-area","Nothing to fetch without area",{layer:e});const f=C(e.sublayers,g,b);if(!f.length)return[];const d=await W(e,f);if(!((e.capabilities?.operations?.supportsIdentify??!0)&&10.5<=e.version||d))throw new x("fetchPopupFeatures:not-supported","query operation is disabled for this service",
{layer:e});return d?this._fetchPopupFeaturesUsingQueries(a,f,b):this._fetchPopupFeaturesUsingIdentify(a,f,b)}clearHighlights(){this.highlightGraphics?.removeAll()}highlight(a){const b=this.highlightGraphics;if(!a||!b)return A.emptyHighlightHandle;let e=E.isGraphic(a)?[a]:G.isCollection(a)?a.toArray():Array.isArray(a)?a:[];e=e?.filter(w.isSome);if(0===(e?.length??0))return A.emptyHighlightHandle;for(const g of e)({sourceLayer:a}=g),null!=a&&"geometryType"in a&&"point"===a.geometryType&&(g.visible=
!1);b.addMany(e);return H.makeHandle(()=>b.removeMany(e??[]))}async _updateHighlightedFeaturesSymbols(a){const {layerView:{view:b},highlightGraphics:e,highlightGraphicUpdated:g}=this;if(e&&g)for(const f of a){const d=f.sourceLayer&&"renderer"in f.sourceLayer&&f.sourceLayer.renderer;f.sourceLayer&&"geometryType"in f.sourceLayer&&"point"===f.sourceLayer.geometryType&&d&&"getSymbolAsync"in d&&d.getSymbolAsync(f).then(async c=>{c||=new z;let h=null;const k="visualVariables"in d?d.visualVariables?.find(l=>
"size"===l.type):void 0;k&&(v||(v=(await new Promise((l,m)=>D(["../../../renderers/visualVariables/support/visualVariableUtils"],l,m))).getSize),h=v(k,f,{view:b.type,scale:b.scale,shape:"simple-marker"===c.type?c.style:null}));h||="width"in c&&"height"in c&&null!=c.width&&null!=c.height?Math.max(c.width,c.height):"size"in c?c.size:16;e.includes(f)&&(f.symbol=new z({style:"square",size:h,xoffset:"xoffset"in c?c.xoffset:0,yoffset:"yoffset"in c?c.yoffset:0}),g(f,"symbol"),f.visible=!0)})}}async _updateHighlightedFeaturesGeometries(a){const {layerView:{layer:b,
view:e},highlightGraphics:g,highlightGraphicUpdated:f}=this;this._highlightGeometriesResolution=a;if(f&&g?.length&&b.capabilities.operations.supportsQuery){var d=this._getTargetResolution(a);a=new Map;for(var c of g)(!this._featuresResolutions.has(c)||this._featuresResolutions.get(c)>d)&&J.getOrCreateMapValue(a,c.sourceLayer,()=>new Map).set(c.getObjectId(),c);c=Array.from(a,([h,k])=>{const l=h.createQuery();l.objectIds=[...k.keys()];l.outFields=[h.objectIdField];l.returnGeometry=!0;l.maxAllowableOffset=
d;l.outSpatialReference=e.spatialReference;return h.queryFeatures(l)});c=await Promise.all(c);if(!this.destroyed)for(const {features:h}of c)for(const k of h)(c=a.get(k.sourceLayer).get(k.getObjectId()))&&g.includes(c)&&(c.geometry=k.geometry,f(c,"geometry"),this._featuresResolutions.set(c,d))}}_getTargetResolution(a){const b=a*M.getMetersPerUnitForSR(this.layerView.view.spatialReference),e=b/16;return 10>=e?0:a/b*e}async _fetchPopupFeaturesUsingIdentify(a,b,e){a=await this._createIdentifyParameters(a,
b,e);if(null==a)return[];({results:e}=await S.identify(this.layerView.layer.parsedUrl,a,e));return e.map(g=>g.feature)}async _createIdentifyParameters(a,b,e){const {floors:g,layer:f,timeExtent:d,view:{spatialReference:c,scale:h}}=this.layerView;if(!b.length)return null;await Promise.all(b.map(({sublayer:r})=>r.load(e).catch(()=>{})));b=Math.min(I("mapservice-popup-identify-max-tolerance"),f.allSublayers.reduce((r,t)=>t.renderer?y.calculateTolerance({renderer:t.renderer,pointerType:e?.pointerType}):
r,2));var k=this.createFetchPopupFeaturesQueryGeometry(a,b);const l=P.getResolutionForScale(h,c),m=Math.round(k.width/l);k=new O({xmin:k.center.x-l*m,ymin:k.center.y-l*m,xmax:k.center.x+l*m,ymax:k.center.y+l*m,spatialReference:k.spatialReference});return new T({floors:g,gdbVersion:"gdbVersion"in f?f.gdbVersion:void 0,geometry:a,height:m,layerOption:"popup",mapExtent:k,returnGeometry:!0,spatialReference:c,sublayers:f.sublayers,timeExtent:d,tolerance:b,width:m})}async _fetchPopupFeaturesUsingQueries(a,
b,e){const {layerView:{floors:g,timeExtent:f}}=this;b=b.map(async({sublayer:d,popupTemplate:c})=>{await d.load(e).catch(()=>{});if(d.capabilities&&!d.capabilities.operations.supportsQuery)return[];var h=d.createQuery(),k=y.calculateTolerance({renderer:d.renderer,pointerType:e?.pointerType}),l=this.createFetchPopupFeaturesQueryGeometry(a,k),m=new Set;const [r]=await Promise.all([B.getRequiredFields(d,c),d.renderer?.collectRequiredFields(m,d.fieldsIndex)]);u.throwIfAborted(e);Q.collectFields(m,d.fieldsIndex,
r);m=Array.from(m).sort();h.geometry=l;h.outFields=m;h.timeExtent=f;m=R.getLayerFloorFilterClause(g,d);h.where=L.sqlAnd(h.where,m);k=this._getTargetResolution(l.width/k);l=await V(c);u.throwIfAborted(e);c="point"===d.geometryType||l&&l.arcadeUtils.hasGeometryOperations(c);c||(h.maxAllowableOffset=k);({features:h}=await d.queryFeatures(h,e));c=c?0:k;h=await X(d,h,e);for(const t of h)this._featuresResolutions.set(t,c);return h});return(await Promise.allSettled(b)).reduce((d,c)=>"fulfilled"===c.status?
[...d,...c.value]:d,[]).filter(w.isSome)}};p.__decorate([q.property({constructOnly:!0})],n.MapServiceLayerViewHelper.prototype,"createFetchPopupFeaturesQueryGeometry",void 0);p.__decorate([q.property({constructOnly:!0})],n.MapServiceLayerViewHelper.prototype,"layerView",void 0);p.__decorate([q.property({constructOnly:!0})],n.MapServiceLayerViewHelper.prototype,"highlightGraphics",void 0);p.__decorate([q.property({constructOnly:!0})],n.MapServiceLayerViewHelper.prototype,"highlightGraphicUpdated",
void 0);p.__decorate([q.property({constructOnly:!0})],n.MapServiceLayerViewHelper.prototype,"updatingHandles",void 0);n.MapServiceLayerViewHelper=p.__decorate([N.subclass("esri.views.layers.support.MapServiceLayerViewHelper")],n.MapServiceLayerViewHelper);n.collectPopupProviders=C;n.isMapServiceLayerView=function(a,b){return"tile"===b.type||"map-image"===b.type};Object.defineProperty(n,Symbol.toStringTag,{value:"Module"})});