// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.31/esri/copyright.txt for details.
//>>built
define("exports ../../core/arrayUtils ../../core/Error ../../core/urlUtils ../../geometry/Extent ../../geometry/SpatialReference ../ogc/crsUtils ../../chunks/datetime".split(" "),function(r,D,ca,da,G,J,N,O){function P(a){if(0<a.spatialReferences.length)return a.spatialReferences;if(a.sublayers)for(const b of a.sublayers)if(a=P(b),0<a.length)return a;return[]}function Q(a){let b=[];for(const c of a)b.push(c),c.sublayers?.length&&(b=b.concat(Q(c.sublayers)),delete c.sublayers);return b}function m(a,
b){for(let c=0;c<b.childNodes.length;c++){const d=b.childNodes[c];if(d.nodeType===Node.ELEMENT_NODE&&d.nodeName===a)return d}return null}function H(a,b){if(null==b)return[];const c=[];for(let d=0;d<b.childNodes.length;d++){const f=b.childNodes[d];f.nodeType===Node.ELEMENT_NODE&&f.nodeName===a&&c.push(f)}return c}function t(a,b,c){return m(a,b)?.textContent??c}function E(a,b,c){if(!a)return null;var d=parseFloat(a.getAttribute("minx")),f=parseFloat(a.getAttribute("miny")),h=parseFloat(a.getAttribute("maxx"));
a=parseFloat(a.getAttribute("maxy"));c?(c=isNaN(f)?-Number.MAX_VALUE:f,d=isNaN(d)?-Number.MAX_VALUE:d,f=isNaN(a)?Number.MAX_VALUE:a,h=isNaN(h)?Number.MAX_VALUE:h):(c=isNaN(d)?-Number.MAX_VALUE:d,d=isNaN(f)?-Number.MAX_VALUE:f,f=isNaN(h)?Number.MAX_VALUE:h,h=isNaN(a)?Number.MAX_VALUE:a);b=new J({wkid:b});return new G({xmin:c,ymin:d,xmax:f,ymax:h,spatialReference:b})}function R(a,b){if(a=m(b,a))if(a=m("DCPType",a))if(a=m("HTTP",a))if(a=m("Get",a))if(b=(a=m("OnlineResource",a))?a.getAttribute("xlink:href")??
null:null){a=b.indexOf("\x26");-1!==a&&a===b.length-1&&(b=b.slice(0,-1));a=["service","request"];const c=[];b=da.urlToObject(b);for(const d in b.query)b.query.hasOwnProperty(d)&&(a.includes(d.toLowerCase())||c.push(d+"\x3d"+b.query[d]));return b.path+(c.length?"?"+c.join("\x26"):"")}return null}function S(a,b){var c=H("Operation",a);if(!c.length)return b=m(b,a),H("Format",b).map(({textContent:d})=>d).filter(D.isSome);a=[];for(const d of c)if(d.getAttribute("name")===b){c=H("Format",d);for(const {textContent:f}of c)null!=
f&&a.push(f)}return a}function T(a,b,c){a=m(b,a);if(!a)return c;({textContent:a}=a);if(null==a||""===a)return c;a=Number(a);return isNaN(a)?c:a}function F(a,b,c){if(!a)return null;const d={id:c.idCounter++,fullExtents:[],parentLayerId:null,queryable:"1"===a.getAttribute("queryable"),spatialReferences:[],sublayers:null},f=m("LatLonBoundingBox",a),h=m("EX_GeographicBoundingBox",a);let n=null;f&&(n=E(f,4326));h&&(n=new G(0,0,0,0,new J({wkid:4326})),n.xmin=parseFloat(t("westBoundLongitude",h,"0")),n.ymin=
parseFloat(t("southBoundLatitude",h,"0")),n.xmax=parseFloat(t("eastBoundLongitude",h,"0")),n.ymax=parseFloat(t("northBoundLatitude",h,"0")));f||h||(n=new G(-180,-90,180,90,new J({wkid:4326})));d.minScale=T(a,"MaxScaleDenominator",0);d.maxScale=T(a,"MinScaleDenominator",0);const y=["1.0.0","1.1.0","1.1.1"].includes(b)?"SRS":"CRS";Array.prototype.slice.call(a.childNodes).forEach(e=>{if("Name"===e.nodeName)d.name=e.textContent||"";else if("Title"===e.nodeName)d.title=e.textContent||"";else if("Abstract"===
e.nodeName)d.description=e.textContent||"";else if("BoundingBox"===e.nodeName){var k=e.getAttribute(y);if(k&&0===k.indexOf("EPSG:")){var p=parseInt(k.slice(5),10);0===p||isNaN(p)||n||(n="1.3.0"===b?E(e,p,N.isAxesOrderReversedForWkid(p)):E(e,p))}(p=k?.indexOf(":"))&&-1<p&&(k=parseInt(k.slice(p+1),10),0===k||isNaN(k)||(k=U[k]??k),(e="1.3.0"===b?E(e,k,N.isAxesOrderReversedForWkid(k)):E(e,k))&&d.fullExtents&&d.fullExtents.push(e))}else if(e.nodeName===y)(e.textContent?.split(" ")??[]).forEach(q=>{let g=
NaN;if(q.includes(":")){const [u,w]=q.toUpperCase().split(":");if("CRS"===u||"EPSG"===u)g=parseInt(w,10)}else g=parseInt(q,10);0===g||isNaN(g)||(q=U[g]??g,d.spatialReferences.includes(q)||d.spatialReferences.push(q))});else if("Style"!==e.nodeName||d.legendUrl)"Layer"===e.nodeName&&(e=F(e,b,c))&&(e.parentLayerId=d.id,d.sublayers||(d.sublayers=[]),d.sublayers.push(e));else if(e=m("LegendURL",e))if(e=m("OnlineResource",e))d.legendUrl=e.getAttribute("xlink:href")});d.extent=n?.toJSON();d.dimensions=
H("Dimension",a).filter(e=>e.getAttribute("name")&&e.getAttribute("units")&&e.textContent).map(e=>{const k=e.getAttribute("name"),p=e.getAttribute("units"),q=e.textContent,g=e.getAttribute("unitSymbol")??void 0,u=e.getAttribute("default")??void 0,w="0"!==(e.getAttribute("default")??"0"),z="0"!==(e.getAttribute("nearestValue")??"0");e="0"!==(e.getAttribute("current")??"0");return I({name:k,units:p})?{name:"time",units:"ISO8601",extent:V(q),default:V(u),multipleValues:w,nearestValue:z,current:e}:K({name:k,
units:p})?{name:"elevation",units:p,extent:W(q),unitSymbol:g,default:W(u),multipleValues:w,nearestValue:z}:{name:k,units:p,extent:X(q),unitSymbol:g,default:X(u),multipleValues:w,nearestValue:z}});return d}function ea(a){return Array.isArray(a)&&0<a.length&&a[0]instanceof Date}function K(a){return/^elevation$/i.test(a.name)&&/^(epsg|crs):\d+$/i.test(a.units)}function I(a){return/^time$/i.test(a.name)&&/^iso8601$/i.test(a.units)}function W(a){if(a){var b=a.includes("/");a=a.split(",");return b?a.map(c=>
{var d=c.split("/");if(2>d.length)return null;c=parseFloat(d[0]);const f=parseFloat(d[1]);d=3<=d.length&&"0"!==d[2]?parseFloat(d[2]):void 0;return{min:c,max:f,resolution:d}}).filter(D.isSome):a.map(c=>parseFloat(c))}}function X(a){if(a){var b=a.includes("/");a=a.split(",");return b?a.map(c=>{c=c.split("/");return 2>c.length?null:{min:c[0],max:c[1],resolution:3<=c.length&&"0"!==c[2]?c[2]:void 0}}).filter(D.isSome):a}}function V(a){if(a){var b=a.includes("/");a=a.split(",");return b?a.map(c=>{var d=
c.split("/");if(2>d.length)return null;c=L(d[0]);const f=L(d[1]);d=3<=d.length&&"0"!==d[2]?Y(d[2]):void 0;return{min:c,max:f,resolution:d}}).filter(D.isSome):a.map(c=>L(c))}}function L(a){return O.DateTime.fromISO(a,{zone:O.FixedOffsetZone.utcInstance}).toJSDate()}function Y(a){var b=a.match(/(?:p(\d+y|\d+(?:\.|,)\d+y)?(\d+m|\d+(?:\.|,)\d+m)?(\d+d|\d+(?:\.|,)\d+d)?)?(?:t(\d+h|\d+(?:\.|,)\d+h)?(\d+m|\d+(?:\.|,)\d+m)?(\d+s|\d+(?:\.|,)\d+s)?)?/i);if(!b)return null;a=B(b[1]);const c=B(b[2]),d=B(b[3]),
f=B(b[4]),h=B(b[5]);b=B(b[6]);return{years:a,months:c,days:d,hours:f,minutes:h,seconds:b}}function B(a){if(!a)return 0;a=a.match(/(?:\d+(?:\.|,)\d+|\d+)/);if(!a)return 0;a=a[0].replace(",",".");return Number(a)}function M(a){return a.toISOString().replace(/\.[0-9]{3}/,"")}const U={84:4326,83:4269,27:4267},Z=new Set([102100,3857,102113,900913]),fa=new Set([3395,54004]);r.fromISODuration=Y;r.getPopupLayers=function(a){a=a.filter(b=>b.popupEnabled&&b.name&&b.queryable);return a.length?a.map(({name:b})=>
b).join():null};r.isDimensionInterval=function(a){return void 0!==a.min&&void 0!==a.max};r.isElevationDimension=K;r.isGenericDimension=function(a){return!I(a)&&!K(a)};r.isTimeDimension=I;r.normalizeWKID=function(a,b){let c=a.wkid;if(null==b)return c;null!=c&&b.includes(c)||!a.latestWkid||(c=a.latestWkid);return null!=c&&Z.has(c)?b.find(d=>Z.has(d))||b.find(d=>fa.has(d))||102100:c};r.parseCapabilities=function(a){if(!a)return null;const b={idCounter:-1};"string"===typeof a&&(a=(new DOMParser).parseFromString(a,
"text/xml"));a=a.documentElement;if("ServiceExceptionReport"===a.nodeName)throw a=Array.prototype.slice.call(a.childNodes).map(l=>l.textContent).join("\r\n"),new ca("wmslayer:wms-capabilities-xml-is-not-valid","The server returned errors when the WMS capabilities were requested.",a);var c=m("Capability",a),d=m("Service",a),f=c&&m("Request",c);if(!c||!d||!f)return null;var h=m("Layer",c);if(!h)return null;const n="WMS_Capabilities"===a.nodeName||"WMT_MS_Capabilities"===a.nodeName?a.getAttribute("version"):
"1.3.0";a=t("Title",d,"")||t("Name",d,"");var y=t("AccessConstraints",d,"");y=/^none$/i.test(y)?"":y;const e=t("Abstract",d,""),k=parseInt(t("MaxWidth",d,"5000"),10);d=parseInt(t("MaxHeight",d,"5000"),10);const p=S(f,"GetMap"),q=R(f,"GetMap"),g=F(h,n,b);if(!g)return null;let u=0,w;c=Array.prototype.slice.call(c.childNodes);const z=g.sublayers??[];c.forEach(l=>{if("Layer"===l.nodeName){if(0===u)w=l;else if(1===u){if(g.name){g.name="";var v=F(w,n,b);null!=v&&z.push(v)}l=F(l,n,b);null!=l&&z.push(l)}else l=
F(l,n,b),null!=l&&z.push(l);u++}});var x=g.sublayers;h=g.extent;c=g.fullExtents??[];x||=[];0===x.length&&x.push(g);h||(h=new G(x[0].extent),g.extent=h.toJSON(),h=g.extent);const ha=0<g.spatialReferences.length?g.spatialReferences:P(g),aa=R(f,"GetFeatureInfo");f=aa?S(f,"GetFeatureInfo"):null;x=Q(x);const ia=g.minScale||0,ja=g.maxScale||0,ba=g.dimensions??[];var C=x.reduce((l,v)=>l.concat(v.dimensions??[]),[]);C=ba.concat(C).filter(I);var A=null;C.length&&(A=C.map(l=>{({extent:l}=l);return ea(l)?l.map(v=>
v.getTime()):l?.map(v=>[v.min.getTime(),v.max.getTime()])}).flat(2).filter(D.isSome),C=Math.min(...A),A=Math.max(...A),A={startTimeField:null,endTimeField:null,trackIdField:void 0,timeExtent:[C,A]});return{copyright:y,description:e,dimensions:ba,extent:h,fullExtents:c,featureInfoFormats:f,featureInfoUrl:aa,mapUrl:q,maxWidth:k,maxHeight:d,maxScale:ja,minScale:ia,layers:x,spatialReferences:ha,supportedImageFormatTypes:p,timeInfo:A,title:a,version:n}};r.toTimeQueryParameter=function(a){if(a&&!a.isAllTime&&
!a.isEmpty){var {start:b,end:c}=a;if(b&&c&&b.getTime()===c.getTime())return`${M(b)}`;a=b?M(b):"0000-01-01T00:00:00Z";var d=c?M(c):"9999-12-31T23:59:59Z";return`${a}/${d}`}};Object.defineProperty(r,Symbol.toStringTag,{value:"Module"})});